"""Generate architecture_v12_4.ipynb — Geometric Transport Architecture.
V12.4 fixes V12.3's manifold disconnect:
  - SSM reads magnitudes only (which modes are active, not their phase)
  - SpectralInteraction uses context-dependent mixing (low-rank perturbation)
  - ComplexMLP replaces real MLP (modReLU preserves phase, complex linear respects geometry)
  - The Interaction IS the transport network, MLP is residual correction."""
import json
import os

cells = []

def md(source):
    lines = source.split("\n")
    source_list = [line + "\n" for line in lines[:-1]] + [lines[-1]]
    cells.append({"cell_type": "markdown", "metadata": {}, "source": source_list})

def code(source):
    lines = source.split("\n")
    source_list = [line + "\n" for line in lines[:-1]] + [lines[-1]]
    cells.append({"cell_type": "code", "metadata": {}, "source": source_list,
                  "outputs": [], "execution_count": None})


# ═══════════════════════════════════════════════════════════════
# CELL 0: Title
# ═══════════════════════════════════════════════════════════════
md(
"# V12.4: Geometric Transport Architecture\n"
"\n"
"## The Problem with V12.3\n"
"\n"
"V12.3 moved to spectral-native processing (no intra-block irfft), but:\n"
"- SSM reads `to_real(spectral_x)` (272-dim) — flattens complex structure, wastes half the input on phase the context doesn't need\n"
"- SpectralInteraction has **fixed** mixing matrices — context only gates output, doesn't reshape the geometry\n"
"- SpectralMLP is a generic real-valued MLP on concatenated real+imag — breaks complex structure, the optimizer routes everything through it because it's the most expressive component\n"
"\n"
"The manifold disconnect: we have geometric operations (interaction, transport) but they're dominated by a non-geometric MLP.\n"
"\n"
"## V12.4: Make the Geometry Primary\n"
"\n"
"Tokens are constellations of active modes. The transport between constellations must\n"
"respect the submanifold structure. Three changes:\n"
"\n"
"### 1. SSM reads magnitudes only (136 real, not 272)\n"
"Context = which modes are active and how strong. Phase is the internal coordinate that\n"
"transport manipulates — the SSM doesn't need to see it.\n"
"\n"
"### 2. Context-dependent SpectralInteraction\n"
"Instead of fixed mixing matrices gated by context, context generates a **low-rank\n"
"perturbation** to the base mixing. The transport matrix itself changes per token,\n"
"per position, based on sequential context. Context reshapes the geometry.\n"
"\n"
"### 3. Complex MLP with modReLU\n"
"Complex-valued linear layers + modReLU (nonlinear on magnitude, transparent to phase).\n"
"Serves as residual correction to the geometric interaction, not the primary computation.\n"
"Cannot trivially bypass the geometry because it operates in the same algebraic structure.\n"
"\n"
"| Component | V12.3 | V12.4 |\n"
"|-----------|-------|-------|\n"
"| SSM input | real+imag concat (272) | magnitudes only (136) |\n"
"| Interaction mixing | fixed W, context gates output | W + context-dependent low-rank ΔW |\n"
"| MLP | real-valued 272→408→272 | complex-valued 136→204→136 with modReLU |\n"
"| Transport role | mode-wise scaling | mode-wise scaling (unchanged) |\n"
"\n"
"## Literature\n"
"\n"
"- **Trabelsi 2018 (Deep Complex Networks)**: Complex-valued layers + modReLU for spectral data\n"
"- **Donoho-Stark 1989**: Spectral sparsity guarantees spatial coverage\n"
"- **Shi 2025**: Reaction-diffusion — interaction IS the reaction, transport IS the diffusion\n"
"- **Li 2026 (DMHN)**: Context reshapes the attractor manifold\n"
"\n"
"## Preserved Non-Negotiables\n"
"\n"
"1. **Sparse in spectral** — 6/17 modes per subbundle, enforced every block\n"
"2. **Field reconstruction IS the irfft** — at decoder output only\n"
"3. **Context warps the spectral metric** — D, A, and now W are context-dependent\n"
"4. **No pairwise token attention**\n"
"5. **Spectral-native** — no irfft inside blocks (carried from V12.3)"
)

# ═══════════════════════════════════════════════════════════════
# CELL 1: Imports + Data
# ═══════════════════════════════════════════════════════════════
code(
"import torch\n"
"import torch.nn as nn\n"
"import torch.nn.functional as F\n"
"import numpy as np\n"
"import matplotlib.pyplot as plt\n"
"from dataclasses import dataclass\n"
"import math\n"
"import time\n"
"import os\n"
"\n"
"if torch.cuda.is_available():\n"
"    device = torch.device(\"cuda\")\n"
"elif hasattr(torch.backends, \"mps\") and torch.backends.mps.is_available():\n"
"    device = torch.device(\"mps\")\n"
"else:\n"
"    device = torch.device(\"cpu\")\n"
"print(f\"Device: {device}\")\n"
"\n"
"DATA_URL = \"https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt\"\n"
"DATA_PATH = os.path.join(os.getcwd(), \"tiny_shakespeare.txt\")\n"
"if not os.path.exists(DATA_PATH):\n"
"    import urllib.request\n"
"    urllib.request.urlretrieve(DATA_URL, DATA_PATH)\n"
"\n"
"with open(DATA_PATH) as f:\n"
"    text = f.read()\n"
"chars = sorted(set(text))\n"
"vocab_size = len(chars)\n"
"stoi = {c: i for i, c in enumerate(chars)}\n"
"itos = {i: c for c, i in stoi.items()}\n"
"data = torch.tensor([stoi[c] for c in text], dtype=torch.long)\n"
"split = int(0.9 * len(data))\n"
"train_data, val_data = data[:split], data[split:]\n"
"print(f\"Tiny Shakespeare: {len(data):,} chars, vocab {vocab_size}\")"
)

# ═══════════════════════════════════════════════════════════════
# CELL 2: Config
# ═══════════════════════════════════════════════════════════════
code(
"@dataclass\n"
"class V12_4Config:\n"
"    fiber_dim: int = 256\n"
"    n_subbundles: int = 8\n"
"    spectral_sparsity: int = 6       # 6/17 = 35% active\n"
"    vocab_size: int = 65\n"
"    max_seq_len: int = 512\n"
"    n_blocks: int = 6\n"
"    context_dim: int = 128\n"
"    interaction_rank: int = 2         # rank of context-dependent perturbation\n"
"    mlp_ratio: float = 1.5\n"
"    modrelu_threshold: float = 0.5   # initial modReLU bias\n"
"    learning_rate: float = 3e-3\n"
"    min_lr: float = 3e-4\n"
"    warmup_steps: int = 750\n"
"    lr_hold_steps: int = 3250\n"
"    dropout: float = 0.1\n"
"    batch_size: int = 16\n"
"    seq_len: int = 512\n"
"    max_steps: int = 10000\n"
"    eval_interval: int = 500\n"
"    eval_steps: int = 10\n"
"\n"
"    @property\n"
"    def subbundle_dim(self):\n"
"        return self.fiber_dim // self.n_subbundles   # 32\n"
"\n"
"    @property\n"
"    def spectral_half_dim(self):\n"
"        return self.subbundle_dim // 2 + 1           # 17\n"
"\n"
"    @property\n"
"    def spectral_dim(self):\n"
"        return self.n_subbundles * self.spectral_half_dim  # 136\n"
"\n"
"    @property\n"
"    def total_active_modes(self):\n"
"        return self.n_subbundles * self.spectral_sparsity  # 48\n"
"\n"
"    @property\n"
"    def mlp_hidden(self):\n"
"        return int(self.spectral_dim * self.mlp_ratio)  # 204 (complex)\n"
"\n"
"\n"
"config = V12_4Config(vocab_size=vocab_size)\n"
"print(f\"Spectral dim: {config.spectral_dim} complex\")\n"
"print(f\"Sparsity: {config.spectral_sparsity}/{config.spectral_half_dim} per subbundle \"\n"
"      f\"= {100*config.spectral_sparsity/config.spectral_half_dim:.0f}% active\")\n"
"print(f\"Blocks: {config.n_blocks}, Context: {config.context_dim}\")\n"
"print(f\"Interaction rank: {config.interaction_rank}\")\n"
"print(f\"Complex MLP hidden: {config.mlp_hidden}\")\n"
"print(f\"Seq len: {config.seq_len}, Batch: {config.batch_size}\")\n"
"\n"
"def get_batch(split_data, cfg):\n"
"    ix = torch.randint(0, len(split_data) - cfg.seq_len - 1, (cfg.batch_size,))\n"
"    return torch.stack([split_data[i:i+cfg.seq_len] for i in ix]).to(device)"
)

# ═══════════════════════════════════════════════════════════════
# CELL 3: Architecture header
# ═══════════════════════════════════════════════════════════════
md(
"## Architecture: Geometric Transport in Spectral Domain\n"
"\n"
"The spectral state is the only state. Complex 136-dim with 6/17 modes active.\n"
"\n"
"SSM reads **magnitudes** (which modes, how strong) to produce context.\n"
"Context generates the **transport geometry** (how modes couple, how energy moves).\n"
"Complex MLP provides residual correction within the complex manifold.\n"
"irfft happens once, at the decoder."
)

# ═══════════════════════════════════════════════════════════════
# CELL 4: Utilities
# ═══════════════════════════════════════════════════════════════
code(
"def spectral_sparsify(x_complex, cfg):\n"
"    \"\"\"Per-subbundle top-k sparsification in spectral domain.\"\"\"\n"
"    shape = x_complex.shape\n"
"    x_subs = x_complex.reshape(*shape[:-1], cfg.n_subbundles, cfg.spectral_half_dim)\n"
"    with torch.no_grad():\n"
"        mags = x_subs.abs()\n"
"        gt_count = (mags.unsqueeze(-1) < mags.unsqueeze(-2)).sum(dim=-1)\n"
"        mask = (gt_count < cfg.spectral_sparsity).float()\n"
"    return (x_subs * mask).reshape(shape)\n"
"\n"
"\n"
"def spectral_to_spatial(x_spectral, cfg):\n"
"    \"\"\"irfft: spectral -> spatial. Used ONLY at decoder.\"\"\"\n"
"    shape = x_spectral.shape[:-1]\n"
"    subs = x_spectral.reshape(*shape, cfg.n_subbundles, cfg.spectral_half_dim)\n"
"    return torch.fft.irfft(subs, n=cfg.subbundle_dim, dim=-1).reshape(*shape, cfg.fiber_dim)\n"
"\n"
"\n"
"def parallel_associative_scan(A, B):\n"
"    _, T, _ = A.shape\n"
"    a, b = A, B\n"
"    for d in range(int(math.ceil(math.log2(T)))):\n"
"        step = 2 ** d\n"
"        if step >= T:\n"
"            break\n"
"        b = torch.cat([b[:, :step, :],\n"
"                        a[:, step:, :] * b[:, :-step, :] + b[:, step:, :]], dim=1)\n"
"        a = torch.cat([a[:, :step, :],\n"
"                        a[:, step:, :] * a[:, :-step, :]], dim=1)\n"
"    return b\n"
"\n"
"\n"
"def modrelu(z, threshold):\n"
"    \"\"\"modReLU: nonlinear on magnitude, transparent to phase.\n"
"    f(z) = ReLU(|z| - threshold) * z / |z|  for |z| > 0\n"
"    Preserves phase, applies soft thresholding to magnitude.\"\"\"\n"
"    mag = z.abs().clamp(min=1e-8)\n"
"    activated_mag = F.relu(mag - threshold)\n"
"    return activated_mag * (z / mag)\n"
"\n"
"\n"
"# Verify modReLU preserves phase\n"
"_z = torch.randn(4, 4) + 1j * torch.randn(4, 4)\n"
"_out = modrelu(_z, 0.5)\n"
"_phase_in = torch.angle(_z)\n"
"_phase_out = torch.angle(_out)\n"
"# Only compare where output is nonzero (active modes)\n"
"_active = _out.abs() > 1e-7\n"
"_err = (_phase_in[_active] - _phase_out[_active]).abs().max().item()\n"
"print(f\"modReLU phase preservation error: {_err:.2e}\")\n"
"print(f\"modReLU kills {(~_active).float().mean():.0%} of modes (threshold=0.5)\")"
)

# ═══════════════════════════════════════════════════════════════
# CELL 5: SpectralTokenEmbedding
# ═══════════════════════════════════════════════════════════════
code(
"class SpectralTokenEmbedding(nn.Module):\n"
"    \"\"\"Tokens -> sparse spectral patterns (constellations of active modes).\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.mag_embedding = nn.Embedding(cfg.vocab_size, cfg.spectral_dim)\n"
"        self.phase_embedding = nn.Embedding(cfg.vocab_size, cfg.spectral_dim)\n"
"        nn.init.uniform_(self.phase_embedding.weight, -math.pi, math.pi)\n"
"        freqs = torch.zeros(cfg.spectral_dim)\n"
"        for k in range(cfg.n_subbundles):\n"
"            off = k * cfg.spectral_half_dim\n"
"            freqs[off:off+cfg.spectral_half_dim] = (\n"
"                2 * math.pi * torch.fft.rfftfreq(cfg.subbundle_dim, d=1.0))\n"
"        self.register_buffer('freqs', freqs)\n"
"\n"
"    def forward(self, token_ids):\n"
"        B, T = token_ids.shape\n"
"        mag = self.mag_embedding(token_ids)\n"
"        phase = self.phase_embedding(token_ids)\n"
"        pos = torch.arange(T, device=token_ids.device).float()\n"
"        total_phase = phase + (pos.unsqueeze(-1) * self.freqs).unsqueeze(0)\n"
"        spectral = mag * torch.exp(1j * total_phase)\n"
"        return spectral_sparsify(spectral, self.cfg)"
)

# ═══════════════════════════════════════════════════════════════
# CELL 6: SpectralNorm
# ═══════════════════════════════════════════════════════════════
code(
"class SpectralNorm(nn.Module):\n"
"    \"\"\"LayerNorm on magnitude. Preserves phase exactly.\"\"\"\n"
"\n"
"    def __init__(self, spectral_dim):\n"
"        super().__init__()\n"
"        self.norm = nn.LayerNorm(spectral_dim)\n"
"\n"
"    def forward(self, x):\n"
"        mag = x.abs().clamp(min=1e-8)\n"
"        phase = x / mag\n"
"        return self.norm(mag) * phase"
)

# ═══════════════════════════════════════════════════════════════
# CELL 7: SpectralSSM (reads magnitudes only)
# ═══════════════════════════════════════════════════════════════
code(
"class SpectralSSM(nn.Module):\n"
"    \"\"\"SSM that reads spectral magnitudes only.\n"
"    Input: |spectral_x| (136 real) — which modes are active, how strong.\n"
"    Output: real-valued context (128-dim) for driving transport geometry.\n"
"\n"
"    The SSM doesn't need phase — it needs the structural summary:\n"
"    which modes are on, how loud they are, how this pattern evolves\n"
"    across the sequence.\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        sd = cfg.spectral_dim          # 136 (magnitudes)\n"
"        cd = cfg.context_dim           # 128\n"
"        self.A_proj = nn.Linear(sd, cd)\n"
"        self.B_proj = nn.Linear(sd, cd)\n"
"        self.psi_proj = nn.Linear(sd, cd)\n"
"\n"
"    def forward(self, spectral_x):\n"
"        x_mag = spectral_x.abs()       # (B, T, 136) — magnitudes only\n"
"        A = torch.sigmoid(self.A_proj(x_mag))\n"
"        B = torch.sigmoid(self.B_proj(x_mag))\n"
"        psi = self.psi_proj(x_mag)\n"
"        return parallel_associative_scan(A, B * psi)"
)

# ═══════════════════════════════════════════════════════════════
# CELL 8: SpectralInteraction (context-dependent mixing)
# ═══════════════════════════════════════════════════════════════
code(
"class SpectralInteraction(nn.Module):\n"
"    \"\"\"Context-dependent geometric transport in spectral domain.\n"
"\n"
"    The mixing matrix W is not fixed — context generates a low-rank perturbation:\n"
"        W(ctx) = W_base + U(ctx) @ V(ctx)\n"
"    where U, V are rank-r projections from the SSM context.\n"
"\n"
"    This means the transport geometry itself changes per token, per position.\n"
"    Context doesn't just scale output — it reshapes HOW modes couple.\n"
"\n"
"    Two levels:\n"
"    1. Intra-subbundle: context-dependent complex mixing via rank-r perturbation\n"
"    2. Cross-subbundle: fixed 8x8 coupling, context gates which subbundles participate\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        K = cfg.n_subbundles           # 8\n"
"        shd = cfg.spectral_half_dim    # 17\n"
"        r = cfg.interaction_rank       # 2\n"
"        cd = cfg.context_dim           # 128\n"
"        self.K, self.shd, self.r = K, shd, r\n"
"\n"
"        # Base mixing matrices (learned, complex)\n"
"        self.intra_real = nn.Parameter(\n"
"            torch.eye(shd).unsqueeze(0).repeat(K, 1, 1) +\n"
"            torch.randn(K, shd, shd) * 0.02)\n"
"        self.intra_imag = nn.Parameter(torch.randn(K, shd, shd) * 0.02)\n"
"\n"
"        # Context -> low-rank perturbation of intra-subbundle mixing\n"
"        # U: (B,T,128) -> (B,T, K*shd*r) real + imag\n"
"        # V: (B,T,128) -> (B,T, K*r*shd) real + imag\n"
"        self.ctx_U_real = nn.Linear(cd, K * shd * r)\n"
"        self.ctx_U_imag = nn.Linear(cd, K * shd * r)\n"
"        self.ctx_V_real = nn.Linear(cd, K * r * shd)\n"
"        self.ctx_V_imag = nn.Linear(cd, K * r * shd)\n"
"        # Scale down initial perturbation\n"
"        for p in [self.ctx_U_real, self.ctx_U_imag, self.ctx_V_real, self.ctx_V_imag]:\n"
"            nn.init.normal_(p.weight, std=0.01)\n"
"            nn.init.zeros_(p.bias)\n"
"\n"
"        # Cross-subbundle: fixed coupling matrix + context gates participation\n"
"        self.cross = nn.Parameter(\n"
"            torch.eye(K).unsqueeze(0).repeat(shd, 1, 1) +\n"
"            torch.randn(shd, K, K) * 0.02)\n"
"        self.ctx_cross_gate = nn.Linear(cd, K)\n"
"        nn.init.zeros_(self.ctx_cross_gate.bias)\n"
"\n"
"        self.gate = nn.Parameter(torch.tensor(-2.0))\n"
"\n"
"    def forward(self, spectral_x, q_t, cfg):\n"
"        K, shd, r = self.K, self.shd, self.r\n"
"        shape = spectral_x.shape[:-1]  # (B, T)\n"
"        subs = spectral_x.reshape(*shape, K, shd)\n"
"\n"
"        # --- Intra-subbundle: W_base + U(ctx) @ V(ctx) ---\n"
"        W_base = torch.complex(self.intra_real, self.intra_imag)  # (K, shd, shd)\n"
"        U = torch.complex(\n"
"            self.ctx_U_real(q_t).reshape(*shape, K, shd, r),\n"
"            self.ctx_U_imag(q_t).reshape(*shape, K, shd, r))     # (B,T,K,shd,r)\n"
"        V = torch.complex(\n"
"            self.ctx_V_real(q_t).reshape(*shape, K, r, shd),\n"
"            self.ctx_V_imag(q_t).reshape(*shape, K, r, shd))     # (B,T,K,r,shd)\n"
"        # Factored form: (W_base + UV)x = W_base*x + U*(V*x)\n"
"        # Never materialize the full (B,T,K,17,17) matrix\n"
"        base_mixed = torch.einsum('...ks,ksd->...kd', subs, W_base)  # (B,T,K,shd)\n"
"        Vx = torch.einsum('...krs,...ks->...kr', V, subs)             # (B,T,K,r) tiny\n"
"        UVx = torch.einsum('...ksr,...kr->...ks', U, Vx)              # (B,T,K,shd)\n"
"        mixed = base_mixed + UVx                                       # (B,T,K,shd)\n"
"        # --- Cross-subbundle: fixed C, context gates which subbundles participate ---\n"
"        cross_gate = torch.sigmoid(\n"
"            self.ctx_cross_gate(q_t)).unsqueeze(-1)                # (B,T,K,1)\n"
"        gated_mixed = mixed * cross_gate                           # gate before coupling\n"
"\n"
"        gated_t = gated_mixed.transpose(-1, -2)                   # (B,T,shd,K)\n"
"        coupled_t = torch.einsum('...fk,fkj->...fj',\n"
"                                 gated_t, self.cross.to(gated_t.dtype))  # (B,T,shd,K)\n"
"        coupled = coupled_t.transpose(-1, -2)                     # (B,T,K,shd)\n"
"\n"
"        g = torch.sigmoid(self.gate)\n"
"        return (subs + g * (coupled - subs)).reshape(*shape, K * shd)"
)

# ═══════════════════════════════════════════════════════════════
# CELL 9: SpectralTransport
# ═══════════════════════════════════════════════════════════════
code(
"class SpectralTransport(nn.Module):\n"
"    \"\"\"Context-dependent spectral kernel: exp(-D*w^2 - i*w*A).\n"
"    Signed diffusion (tanh). Per-mode scaling and phase shift.\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.D_proj = nn.Linear(cfg.context_dim, cfg.spectral_dim)\n"
"        self.A_proj = nn.Linear(cfg.context_dim, cfg.spectral_dim)\n"
"\n"
"    def forward(self, spectral_x, q_t):\n"
"        cfg = self.cfg\n"
"        D = torch.tanh(self.D_proj(q_t))\n"
"        A = self.A_proj(q_t)\n"
"        w = torch.fft.rfftfreq(cfg.subbundle_dim, d=1.0, device=spectral_x.device)\n"
"        w = w.repeat(cfg.n_subbundles)\n"
"        kernel = torch.exp(-D * w**2 - 1j * w * A)\n"
"        return spectral_x * kernel"
)

# ═══════════════════════════════════════════════════════════════
# CELL 10: ComplexMLP (with modReLU)
# ═══════════════════════════════════════════════════════════════
code(
"class ComplexLinear(nn.Module):\n"
"    \"\"\"Linear layer operating on complex tensors: W*z + b, W,b in C.\n"
"    A complex matmul naturally expresses rotations and scalings.\"\"\"\n"
"\n"
"    def __init__(self, in_dim, out_dim):\n"
"        super().__init__()\n"
"        self.W_real = nn.Linear(in_dim, out_dim, bias=False)\n"
"        self.W_imag = nn.Linear(in_dim, out_dim, bias=False)\n"
"        self.bias_real = nn.Parameter(torch.zeros(out_dim))\n"
"        self.bias_imag = nn.Parameter(torch.zeros(out_dim))\n"
"        # Glorot init scaled for complex\n"
"        scale = 1.0 / math.sqrt(2 * in_dim)\n"
"        nn.init.uniform_(self.W_real.weight, -scale, scale)\n"
"        nn.init.uniform_(self.W_imag.weight, -scale, scale)\n"
"\n"
"    def forward(self, z):\n"
"        # (a+bi)(c+di) = (ac-bd) + (ad+bc)i\n"
"        real = self.W_real(z.real) - self.W_imag(z.imag) + self.bias_real\n"
"        imag = self.W_real(z.imag) + self.W_imag(z.real) + self.bias_imag\n"
"        return torch.complex(real, imag)\n"
"\n"
"\n"
"class ComplexMLP(nn.Module):\n"
"    \"\"\"Complex-valued MLP with modReLU activation.\n"
"    Residual correction to the geometric interaction.\n"
"    Operates in complex space — never splits to real+imag.\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        sd = cfg.spectral_dim   # 136 complex\n"
"        hd = cfg.mlp_hidden     # 204 complex\n"
"        self.fc1 = ComplexLinear(sd, hd)\n"
"        self.fc2 = ComplexLinear(hd, sd)\n"
"        self.threshold = nn.Parameter(\n"
"            torch.full((hd,), cfg.modrelu_threshold))\n"
"        self.drop_rate = cfg.dropout\n"
"\n"
"    def forward(self, z):\n"
"        h = modrelu(self.fc1(z), self.threshold)\n"
"        out = self.fc2(h)\n"
"        if self.training and self.drop_rate > 0:\n"
"            mask = torch.rand(out.shape[:-1] + (1,),\n"
"                              device=out.device) > self.drop_rate\n"
"            out = out * mask / (1 - self.drop_rate)\n"
"        return out"
)

# ═══════════════════════════════════════════════════════════════
# CELL 11: V12_4Block
# ═══════════════════════════════════════════════════════════════
code(
"class V12_4Block(nn.Module):\n"
"    \"\"\"Geometric transport block. Spectral-native, complex-native.\n"
"\n"
"    spectral_x -> SSM(|spectral_x|) -> context\n"
"    spectral_x -> Interaction(context) -> Transport(context) ->\n"
"    SpectralNorm -> ComplexMLP -> spectral residual -> sparsify\n"
"\n"
"    The Interaction IS the transport network. Context generates the\n"
"    transport geometry. ComplexMLP is residual correction.\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.ssm = SpectralSSM(cfg)\n"
"        self.interact = SpectralInteraction(cfg)\n"
"        self.transport = SpectralTransport(cfg)\n"
"        self.norm = SpectralNorm(cfg.spectral_dim)\n"
"        self.mlp = ComplexMLP(cfg)\n"
"        self.res_gate = nn.Parameter(torch.tensor(0.5))\n"
"\n"
"    def forward(self, spectral_x):\n"
"        cfg = self.cfg\n"
"\n"
"        # 1. SSM reads magnitudes -> context (which modes, how strong)\n"
"        q_t = self.ssm(spectral_x)\n"
"\n"
"        # 2. Context-dependent geometric transport\n"
"        interacted = self.interact(spectral_x, q_t, cfg)\n"
"\n"
"        # 3. Per-mode scaling + phase shift\n"
"        transported = self.transport(interacted, q_t)\n"
"\n"
"        # 4. Complex nonlinear correction\n"
"        normed = self.norm(transported)\n"
"        mlp_out = self.mlp(normed)\n"
"\n"
"        # 5. Spectral residual + enforce sparsity\n"
"        gate = torch.sigmoid(self.res_gate)\n"
"        spectral_out = spectral_x + gate * mlp_out\n"
"        return spectral_sparsify(spectral_out, cfg)"
)

# ═══════════════════════════════════════════════════════════════
# CELL 12: V12_4Model + GPT + SSM baselines + instantiate
# ═══════════════════════════════════════════════════════════════
code(
"class V12_4Model(nn.Module):\n"
"    \"\"\"Geometric transport CLM. Deep supervision at blocks 2, 4, 6.\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.embedding = SpectralTokenEmbedding(cfg)\n"
"        self.blocks = nn.ModuleList([V12_4Block(cfg) for _ in range(cfg.n_blocks)])\n"
"        self.final_norm = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.decoder = nn.Sequential(\n"
"            nn.Linear(cfg.fiber_dim, cfg.fiber_dim), nn.SiLU(),\n"
"            nn.Dropout(cfg.dropout),\n"
"            nn.Linear(cfg.fiber_dim, cfg.vocab_size),\n"
"        )\n"
"        weights = torch.zeros(cfg.n_blocks)\n"
"        for i in range(cfg.n_blocks):\n"
"            if (i + 1) % 2 == 0:\n"
"                weights[i] = (i + 1) / cfg.n_blocks\n"
"        weights[-1] = 1.0\n"
"        self.register_buffer('block_loss_weights', weights)\n"
"\n"
"    def _decode(self, spectral_x):\n"
"        \"\"\"spectral -> irfft -> spatial -> logits. The ONLY irfft.\"\"\"\n"
"        spatial = spectral_to_spatial(spectral_x, self.cfg)\n"
"        return self.decoder(self.final_norm(spatial))\n"
"\n"
"    def forward(self, token_ids):\n"
"        cfg = self.cfg\n"
"        spectral_x = self.embedding(token_ids)\n"
"        intermediate_logits = []\n"
"        for i, block in enumerate(self.blocks):\n"
"            spectral_x = block(spectral_x)\n"
"            if self.block_loss_weights[i] > 0:\n"
"                logits = self._decode(spectral_x)[:, :-1, :]\n"
"                intermediate_logits.append((logits, self.block_loss_weights[i]))\n"
"        sp = (spectral_x.abs() < 1e-6).float().mean().item()\n"
"        return intermediate_logits[-1][0], {\n"
"            'spectral_sparsity': sp,\n"
"            'intermediate_logits': intermediate_logits,\n"
"        }\n"
"\n"
"\n"
"# -- GPT-Nano ---------------------------------------------------------------\n"
"\n"
"class GPTNano(nn.Module):\n"
"    def __init__(self, vocab_size=65, n_embd=128, n_head=4, n_layer=12,\n"
"                 block_size=512, dropout=0.1):\n"
"        super().__init__()\n"
"        self.block_size = block_size\n"
"        self.tok_emb = nn.Embedding(vocab_size, n_embd)\n"
"        self.pos_emb = nn.Embedding(block_size, n_embd)\n"
"        self.drop = nn.Dropout(dropout)\n"
"        self.blocks = nn.ModuleList()\n"
"        for _ in range(n_layer):\n"
"            self.blocks.append(nn.ModuleDict({\n"
"                'ln1': nn.LayerNorm(n_embd),\n"
"                'attn_qkv': nn.Linear(n_embd, 3 * n_embd),\n"
"                'attn_proj': nn.Linear(n_embd, n_embd),\n"
"                'ln2': nn.LayerNorm(n_embd),\n"
"                'mlp_fc1': nn.Linear(n_embd, 4 * n_embd),\n"
"                'mlp_fc2': nn.Linear(4 * n_embd, n_embd),\n"
"            }))\n"
"        self.ln_f = nn.LayerNorm(n_embd)\n"
"        self.lm_head = nn.Linear(n_embd, vocab_size, bias=False)\n"
"        self.n_head = n_head\n"
"        self.n_embd = n_embd\n"
"        self.register_buffer('causal_mask',\n"
"            torch.tril(torch.ones(block_size, block_size)).view(1,1,block_size,block_size))\n"
"\n"
"    def forward(self, idx):\n"
"        B, T = idx.shape\n"
"        x = self.drop(self.tok_emb(idx) + self.pos_emb(torch.arange(T, device=idx.device)))\n"
"        hd = self.n_embd // self.n_head\n"
"        for blk in self.blocks:\n"
"            h = blk['ln1'](x)\n"
"            qkv = blk['attn_qkv'](h).reshape(B, T, 3, self.n_head, hd)\n"
"            q, k, v = qkv.unbind(2)\n"
"            q, k, v = q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)\n"
"            att = (q @ k.transpose(-2,-1)) * (hd**-0.5)\n"
"            att = att.masked_fill(self.causal_mask[:,:,:T,:T]==0, float('-inf'))\n"
"            y = (F.softmax(att, dim=-1) @ v).transpose(1,2).reshape(B, T, self.n_embd)\n"
"            x = x + blk['attn_proj'](y)\n"
"            x = x + blk['mlp_fc2'](F.gelu(blk['mlp_fc1'](blk['ln2'](x))))\n"
"        return self.lm_head(self.ln_f(x))[:, :-1, :], {}\n"
"\n"
"\n"
"# -- SSM+MLP Only (dense spatial, no spectral domain) -----------------------\n"
"\n"
"class SSMOnlyBlock(nn.Module):\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.A_proj = nn.Linear(cfg.fiber_dim, cfg.context_dim)\n"
"        self.B_proj = nn.Linear(cfg.fiber_dim, cfg.context_dim)\n"
"        self.psi_proj = nn.Linear(cfg.fiber_dim, cfg.context_dim)\n"
"        self.ctx_proj = nn.Linear(cfg.context_dim, cfg.fiber_dim)\n"
"        self.mlp_fc1 = nn.Linear(cfg.fiber_dim, int(cfg.fiber_dim * cfg.mlp_ratio))\n"
"        self.mlp_fc2 = nn.Linear(int(cfg.fiber_dim * cfg.mlp_ratio), cfg.fiber_dim)\n"
"        self.norm1 = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.norm2 = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.drop = nn.Dropout(cfg.dropout)\n"
"        self.gate = nn.Parameter(torch.tensor(0.5))\n"
"\n"
"    def forward(self, x):\n"
"        A = torch.sigmoid(self.A_proj(x))\n"
"        B = torch.sigmoid(self.B_proj(x))\n"
"        psi = self.psi_proj(x)\n"
"        q = parallel_associative_scan(A, B * psi)\n"
"        h = self.norm1(x + self.ctx_proj(q))\n"
"        mlp = self.drop(self.mlp_fc2(F.silu(self.mlp_fc1(self.norm2(h)))))\n"
"        return x + torch.sigmoid(self.gate) * mlp\n"
"\n"
"\n"
"class SSMOnlyModel(nn.Module):\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.emb = nn.Embedding(cfg.vocab_size, cfg.fiber_dim)\n"
"        self.pos = nn.Embedding(cfg.max_seq_len, cfg.fiber_dim)\n"
"        self.drop = nn.Dropout(cfg.dropout)\n"
"        self.blocks = nn.ModuleList([SSMOnlyBlock(cfg) for _ in range(cfg.n_blocks)])\n"
"        self.norm = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.head = nn.Sequential(\n"
"            nn.Linear(cfg.fiber_dim, cfg.fiber_dim), nn.SiLU(),\n"
"            nn.Dropout(cfg.dropout),\n"
"            nn.Linear(cfg.fiber_dim, cfg.vocab_size),\n"
"        )\n"
"\n"
"    def forward(self, ids):\n"
"        x = self.drop(self.emb(ids) + self.pos(torch.arange(ids.size(1), device=ids.device)))\n"
"        for blk in self.blocks:\n"
"            x = blk(x)\n"
"        logits = self.head(self.norm(x))[:, :-1, :]\n"
"        return logits, {'spectral_sparsity': 0.0, 'intermediate_logits': [(logits, 1.0)]}\n"
"\n"
"\n"
"# -- Instantiate -------------------------------------------------------------\n"
"model = V12_4Model(config).to(device)\n"
"gpt_model = GPTNano(vocab_size=vocab_size, block_size=config.seq_len).to(device)\n"
"ssm_model = SSMOnlyModel(config).to(device)\n"
"\n"
"def count_params(m):\n"
"    return sum(p.numel() for p in m.parameters())\n"
"\n"
"print(f\"V12.4:       {count_params(model):>10,} params\")\n"
"print(f\"GPT-Nano:    {count_params(gpt_model):>10,} params\")\n"
"print(f\"SSM+MLP:     {count_params(ssm_model):>10,} params\")\n"
"\n"
"n_e = sum(p.numel() for p in model.embedding.parameters())\n"
"n_ssm = sum(sum(p.numel() for p in b.ssm.parameters()) for b in model.blocks)\n"
"n_int = sum(sum(p.numel() for p in b.interact.parameters()) for b in model.blocks)\n"
"n_trn = sum(sum(p.numel() for p in b.transport.parameters()) for b in model.blocks)\n"
"n_mlp = sum(sum(p.numel() for p in b.mlp.parameters()) for b in model.blocks)\n"
"n_dec = sum(p.numel() for p in model.decoder.parameters()) + \\\n"
"        sum(p.numel() for p in model.final_norm.parameters())\n"
"n_oth = count_params(model) - (n_e + n_ssm + n_int + n_trn + n_mlp + n_dec)\n"
"tot = count_params(model)\n"
"print(f\"\\nV12.4 Breakdown:\")\n"
"print(f\"  Embedding:           {n_e:>8,} ({100*n_e/tot:.1f}%)\")\n"
"print(f\"  SpectralSSM:         {n_ssm:>8,} ({100*n_ssm/tot:.1f}%)\")\n"
"print(f\"  SpectralInteraction: {n_int:>8,} ({100*n_int/tot:.1f}%)\")\n"
"print(f\"  SpectralTransport:   {n_trn:>8,} ({100*n_trn/tot:.1f}%)\")\n"
"print(f\"  ComplexMLP:          {n_mlp:>8,} ({100*n_mlp/tot:.1f}%)\")\n"
"print(f\"  Decoder:             {n_dec:>8,} ({100*n_dec/tot:.1f}%)\")\n"
"print(f\"  Other (norms,gates): {n_oth:>8,} ({100*n_oth/tot:.1f}%)\")"
)

# ═══════════════════════════════════════════════════════════════
# CELL 13: Training header
# ═══════════════════════════════════════════════════════════════
md("## Training")

# ═══════════════════════════════════════════════════════════════
# CELL 14: Training functions
# ═══════════════════════════════════════════════════════════════
code(
"@torch.no_grad()\n"
"def estimate_loss(model, cfg, is_gpt=False):\n"
"    model.eval()\n"
"    results = {}\n"
"    for name, sd in [('train', train_data), ('val', val_data)]:\n"
"        tot_ce, tot_ok, tot_n, tot_sp = 0., 0, 0, 0.\n"
"        for _ in range(cfg.eval_steps):\n"
"            b = get_batch(sd, cfg)\n"
"            logits, info = model(b)\n"
"            tgt = b[:, 1:]\n"
"            ce = F.cross_entropy(logits.reshape(-1, cfg.vocab_size), tgt.reshape(-1))\n"
"            tot_ce += ce.item()\n"
"            tot_ok += (logits.argmax(-1) == tgt).sum().item()\n"
"            tot_n += tgt.numel()\n"
"            if not is_gpt:\n"
"                tot_sp += info.get('spectral_sparsity', 0.0)\n"
"        n = cfg.eval_steps\n"
"        results[name] = {\n"
"            'ce': tot_ce/n, 'acc': tot_ok/tot_n,\n"
"            'sparsity': tot_sp/n if not is_gpt else 0.0}\n"
"    model.train()\n"
"    return results\n"
"\n"
"\n"
"def train_model(model, cfg, label='V12.4', is_gpt=False, is_ssm_only=False):\n"
"    opt = torch.optim.AdamW(model.parameters(), lr=cfg.learning_rate, weight_decay=0.05)\n"
"    mr = getattr(cfg, 'min_lr', 0) / cfg.learning_rate\n"
"    he = cfg.warmup_steps + getattr(cfg, 'lr_hold_steps', 0)\n"
"\n"
"    def lr_fn(s):\n"
"        if s < cfg.warmup_steps: return s / max(1, cfg.warmup_steps)\n"
"        if s < he: return 1.0\n"
"        p = (s - he) / max(1, cfg.max_steps - he)\n"
"        return max(mr, 0.5 * (1.0 + math.cos(math.pi * p)))\n"
"\n"
"    sched = torch.optim.lr_scheduler.LambdaLR(opt, lr_fn)\n"
"    hist = {'step':[], 'train_ce':[], 'val_ce':[], 'train_acc':[], 'val_acc':[],\n"
"            'train_bpc':[], 'val_bpc':[], 'sparsity':[], 'lr':[],\n"
"            'step_times':[], 'per_step_loss':[]}\n"
"\n"
"    model.train()\n"
"    t0 = time.time()\n"
"    np_ = count_params(model)\n"
"    print(f\"\\nTraining {label}: {np_:,} params\")\n"
"    print(f\"Steps: {cfg.max_steps}, Batch: {cfg.batch_size}, Seq: {cfg.seq_len}\")\n"
"    print('=' * 70)\n"
"\n"
"    for step in range(cfg.max_steps + 1):\n"
"        if step % cfg.eval_interval == 0:\n"
"            r = estimate_loss(model, cfg, is_gpt=is_gpt)\n"
"            tr, vl = r['train'], r['val']\n"
"            hist['step'].append(step)\n"
"            hist['train_ce'].append(tr['ce']); hist['val_ce'].append(vl['ce'])\n"
"            hist['train_acc'].append(tr['acc']); hist['val_acc'].append(vl['acc'])\n"
"            hist['train_bpc'].append(tr['ce']/math.log(2))\n"
"            hist['val_bpc'].append(vl['ce']/math.log(2))\n"
"            hist['sparsity'].append(vl['sparsity'])\n"
"            hist['lr'].append(sched.get_last_lr()[0])\n"
"            sp = f\" | Sp: {vl['sparsity']:.1%}\" if not is_gpt else ''\n"
"            print(f\"[{label}] Step {step:5d} | Train CE: {tr['ce']:.3f} | \"\n"
"                  f\"Val CE: {vl['ce']:.3f} | Val BPC: {vl['ce']/math.log(2):.3f} | \"\n"
"                  f\"Acc: {vl['acc']:.1%}{sp}\")\n"
"\n"
"        if step >= cfg.max_steps: break\n"
"        st = time.time()\n"
"        batch = get_batch(train_data, cfg)\n"
"        opt.zero_grad()\n"
"        logits, info = model(batch)\n"
"        tgt = batch[:, 1:]\n"
"\n"
"        if is_gpt or is_ssm_only:\n"
"            loss = F.cross_entropy(logits.reshape(-1, cfg.vocab_size), tgt.reshape(-1))\n"
"        else:\n"
"            ce, tw = 0., 0.\n"
"            for bl, w in info['intermediate_logits']:\n"
"                ce += w * F.cross_entropy(bl.reshape(-1, cfg.vocab_size), tgt.reshape(-1))\n"
"                tw += w\n"
"            loss = ce / tw\n"
"\n"
"        loss.backward()\n"
"        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n"
"        opt.step(); sched.step()\n"
"        hist['step_times'].append(time.time() - st)\n"
"        hist['per_step_loss'].append(loss.item())\n"
"        if step % 500 == 0 and step > 0:\n"
"            print(f\"    avg step time: {np.mean(hist['step_times'][-500:])*1000:.0f}ms\")\n"
"\n"
"    el = time.time() - t0\n"
"    ms = np.mean(hist['step_times']) * 1000\n"
"    print(f\"\\n{label} DONE in {el/60:.1f}min | BPC: {hist['val_bpc'][-1]:.3f} | \"\n"
"          f\"Acc: {hist['val_acc'][-1]:.1%} | {ms:.0f}ms/step\")\n"
"    hist['avg_step_ms'] = ms; hist['n_params'] = np_\n"
"    return hist"
)

# ═══════════════════════════════════════════════════════════════
# CELL 15-18: Train all three
# ═══════════════════════════════════════════════════════════════
code("v12_hist = train_model(model, config, label='V12.4')")
md("## Baselines\nGPT-Nano (12-layer attention) and SSM+MLP (no spectral domain). Same schedule.")
code("gpt_hist = train_model(gpt_model, config, label='GPT', is_gpt=True)")
code("ssm_hist = train_model(ssm_model, config, label='SSM+MLP', is_ssm_only=True)")

# ═══════════════════════════════════════════════════════════════
# CELL 19: Results header
# ═══════════════════════════════════════════════════════════════
md("## Results")

# ═══════════════════════════════════════════════════════════════
# CELL 20: Plots
# ═══════════════════════════════════════════════════════════════
code(
"fig, axes = plt.subplots(3, 3, figsize=(18, 15))\n"
"fig.suptitle('V12.4 (Geometric Transport) vs GPT-Nano vs SSM+MLP — seq_len=512',\n"
"             fontsize=16, fontweight='bold')\n"
"hs = [(v12_hist,'V12.4','b','o'), (gpt_hist,'GPT','r','s'), (ssm_hist,'SSM+MLP','g','^')]\n"
"\n"
"for ax, key, title in [(axes[0,0],'val_ce','Val CE'), (axes[0,1],'val_bpc','Val BPC'),\n"
"                        (axes[0,2],'val_acc','Val Accuracy')]:\n"
"    for h,l,c,m in hs:\n"
"        y = [v*100 for v in h[key]] if 'acc' in key else h[key]\n"
"        ax.plot(h['step'], y, f'{c}-{m}', label=l, markersize=3)\n"
"    ax.set_xlabel('Step'); ax.set_title(title); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[1,0]\n"
"w = 100\n"
"for h,l,c,m in hs:\n"
"    if len(h['per_step_loss']) > w:\n"
"        sm = np.convolve(h['per_step_loss'], np.ones(w)/w, mode='valid')\n"
"        ax.plot(range(len(sm)), sm, f'{c}-', label=l, alpha=0.8)\n"
"ax.set_title(f'Step Loss (smooth {w})'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[1,1]\n"
"for h,l,c,m in hs: ax.plot(h['step'], h['lr'], f'{c}-', label=l)\n"
"ax.set_title('LR'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[1,2]\n"
"ax.plot(v12_hist['step'], [s*100 for s in v12_hist['sparsity']], 'b-o', markersize=3)\n"
"ax.axhline(y=100*(1-config.spectral_sparsity/config.spectral_half_dim), color='r', ls=':', label='Target')\n"
"ax.set_title('V12.4 Spectral Sparsity'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[2,0]\n"
"for h,l,c,m in hs:\n"
"    if len(h['step_times']) > w:\n"
"        t = np.convolve([x*1000 for x in h['step_times']], np.ones(w)/w, mode='valid')\n"
"        ax.plot(range(len(t)), t, f'{c}-', label=l, alpha=0.8)\n"
"ax.set_title('ms/step'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[2,1]\n"
"for h,l,c,m in hs:\n"
"    ax.plot(h['step'], [t-v for t,v in zip(h['train_bpc'],h['val_bpc'])], f'{c}-{m}', label=l, ms=3)\n"
"ax.axhline(y=0, color='k', ls=':', alpha=0.3); ax.set_title('Gen. Gap'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[2,2]; ax.axis('off')\n"
"rows = [[l, f'{h[\"n_params\"]:,}', f'{h[\"val_bpc\"][-1]:.3f}', f'{h[\"val_acc\"][-1]:.1%}', f'{h[\"avg_step_ms\"]:.0f}']\n"
"        for h,l,_,_ in hs]\n"
"t = ax.table(cellText=rows, colLabels=['Model','Params','BPC','Acc','ms/step'], loc='center', cellLoc='center')\n"
"t.auto_set_font_size(False); t.set_fontsize(11); t.scale(1.2,1.8)\n"
"ax.set_title('Final Results', fontweight='bold', pad=20)\n"
"plt.tight_layout(); plt.savefig('v12_4_results.png', dpi=150, bbox_inches='tight'); plt.show()\n"
"\n"
"print('\\n' + '='*70 + '\\nRESULTS\\n' + '='*70)\n"
"v,g,s = v12_hist['val_bpc'][-1], gpt_hist['val_bpc'][-1], ssm_hist['val_bpc'][-1]\n"
"print(f\"V12.4:    BPC {v:.3f} | Acc {v12_hist['val_acc'][-1]:.1%} | {v12_hist['avg_step_ms']:.0f}ms\")\n"
"print(f\"GPT-Nano: BPC {g:.3f} | Acc {gpt_hist['val_acc'][-1]:.1%} | {gpt_hist['avg_step_ms']:.0f}ms\")\n"
"print(f\"SSM+MLP:  BPC {s:.3f} | Acc {ssm_hist['val_acc'][-1]:.1%} | {ssm_hist['avg_step_ms']:.0f}ms\")\n"
"print(f\"\\nSpectral contribution: {s - v:+.3f} BPC\")\n"
"print('  -> SPECTRAL CONTRIBUTES!' if v < s - 0.02 else\n"
"      '  -> Spectral hurts.' if v > s + 0.02 else '  -> Marginal.')"
)

# ═══════════════════════════════════════════════════════════════
# CELL 21: Diagnostics header
# ═══════════════════════════════════════════════════════════════
md("## Diagnostics: Is the Geometry Active?")

# ═══════════════════════════════════════════════════════════════
# CELL 22: Diagnostics
# ═══════════════════════════════════════════════════════════════
code(
"@torch.no_grad()\n"
"def diagnostics(model, cfg):\n"
"    model.eval()\n"
"    batch = get_batch(val_data, cfg)\n"
"    sx = model.embedding(batch)\n"
"    print(f'Embedding sparsity: {(sx.abs()<1e-6).float().mean():.1%}')\n"
"\n"
"    print('\\n--- Per-block ---')\n"
"    for i, blk in enumerate(model.blocks):\n"
"        pre = sx.clone()\n"
"        q = blk.ssm(sx)\n"
"\n"
"        # Measure interaction contribution\n"
"        post_int = blk.interact(sx, q, cfg)\n"
"        int_delta = (post_int - sx).abs().mean().item()\n"
"        int_gate = torch.sigmoid(blk.interact.gate).item()\n"
"\n"
"        # Measure context-dependent perturbation magnitude\n"
"        K, shd, r = blk.interact.K, blk.interact.shd, blk.interact.r\n"
"        shape = sx.shape[:-1]\n"
"        U = torch.complex(\n"
"            blk.interact.ctx_U_real(q).reshape(*shape, K, shd, r),\n"
"            blk.interact.ctx_U_imag(q).reshape(*shape, K, shd, r))\n"
"        V = torch.complex(\n"
"            blk.interact.ctx_V_real(q).reshape(*shape, K, r, shd),\n"
"            blk.interact.ctx_V_imag(q).reshape(*shape, K, r, shd))\n"
"        dW = (U @ V).abs().mean().item()\n"
"        W_base = torch.complex(blk.interact.intra_real, blk.interact.intra_imag).abs().mean().item()\n"
"\n"
"        sx = blk(sx)\n"
"        sp = (sx.abs() < 1e-6).float().mean().item()\n"
"        mag = sx.abs().mean().item()\n"
"        gate = torch.sigmoid(blk.res_gate).item()\n"
"\n"
"        # Mode diversity per subbundle\n"
"        subs = sx.reshape(*sx.shape[:-1], cfg.n_subbundles, cfg.spectral_half_dim)\n"
"        active = (subs.abs() > 1e-6).float().mean(dim=(0,1))\n"
"        div = active.std(dim=-1).mean().item()\n"
"\n"
"        print(f'Block {i+1}: sp={sp:.1%} mag={mag:.4f} gate={gate:.3f} '\n"
"              f'int_delta={int_delta:.4f} int_gate={int_gate:.3f} '\n"
"              f'dW/W={dW/max(W_base,1e-8):.3f} mode_div={div:.3f}')\n"
"\n"
"    print('\\n--- modReLU thresholds ---')\n"
"    for i, blk in enumerate(model.blocks):\n"
"        th = blk.mlp.threshold\n"
"        print(f'  Block {i+1}: mean={th.mean():.3f} std={th.std():.3f} '\n"
"              f'min={th.min():.3f} max={th.max():.3f}')\n"
"\n"
"    print('\\n--- Transport D (diffusion) ---')\n"
"    sx = model.embedding(batch)\n"
"    for i, blk in enumerate(model.blocks):\n"
"        q = blk.ssm(sx)\n"
"        D = torch.tanh(blk.transport.D_proj(q))\n"
"        print(f'  Block {i+1}: mean={D.mean():.3f} std={D.std():.3f} neg={100*(D<0).float().mean():.0f}%')\n"
"        sx = blk(sx)\n"
"    model.train()\n"
"\n"
"diagnostics(model, config)"
)

# ═══════════════════════════════════════════════════════════════
# CELL 23: Text gen
# ═══════════════════════════════════════════════════════════════
code(
"@torch.no_grad()\n"
"def gen(model, prompt, cfg, n=200, temp=0.8, is_gpt=False):\n"
"    model.eval()\n"
"    ids = torch.tensor([stoi[c] for c in prompt], dtype=torch.long, device=device).unsqueeze(0)\n"
"    for _ in range(n):\n"
"        ctx = ids[:, -cfg.seq_len:]\n"
"        logits, _ = model(ctx)\n"
"        p = F.softmax(logits[:, -1, :] / temp, dim=-1)\n"
"        ids = torch.cat([ids, torch.multinomial(p, 1)], dim=1)\n"
"    return ''.join(itos[i.item()] for i in ids[0])\n"
"\n"
"for p in ['ROMEO:\\n', 'To be or not to ', 'The king ']:\n"
"    print(f\"\\nPrompt: {repr(p)}\")\n"
"    print(f\"  V12.4:   {gen(model, p, config)[len(p):len(p)+120]}\")\n"
"    print(f\"  GPT:     {gen(gpt_model, p, config, is_gpt=True)[len(p):len(p)+120]}\")\n"
"    print(f\"  SSM+MLP: {gen(ssm_model, p, config)[len(p):len(p)+120]}\")"
)

# ═══════════════════════════════════════════════════════════════
# CELL 24: Summary
# ═══════════════════════════════════════════════════════════════
md(
"## Summary: V12.4 Geometric Transport\n"
"\n"
"**Core change:** The geometry is primary. Context doesn't just gate output — it\n"
"reshapes the transport matrices. The optimizer can't bypass geometry because the\n"
"ComplexMLP operates in the same algebraic structure as the interaction.\n"
"\n"
"**Block flow:**\n"
"```\n"
"spectral_x (136 complex, sparse 6/17) ->\n"
"  SpectralSSM(|x|) -> context (128 real) ->\n"
"  SpectralInteraction(W_base + U(ctx)@V(ctx), C_base + dC(ctx)) ->\n"
"  SpectralTransport(exp(-D*w^2 - i*w*A)) ->\n"
"  SpectralNorm -> ComplexMLP(136 -> 204 -> 136, modReLU) ->\n"
"  spectral residual + sparsify -> spectral_out\n"
"```\n"
"\n"
"**Three fixes from V12.3:**\n"
"1. SSM reads magnitudes (136 real) not real+imag (272). Better signal, half the cost.\n"
"2. Interaction mixing is context-dependent (low-rank ΔW). Context reshapes geometry.\n"
"3. Complex MLP with modReLU. Phase-preserving nonlinearity. Residual correction,\n"
"   not primary computation.\n"
"\n"
"**Key diagnostic:** `dW/W` ratio shows how much context perturbs the base mixing.\n"
"If this grows during training, the model is learning to use context-dependent transport.\n"
"If it stays near zero, context isn't reshaping the geometry."
)

# ═══════════════════════════════════════════════════════════════
# Write notebook
# ═══════════════════════════════════════════════════════════════
nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "base", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"}
    },
    "cells": cells,
}

outpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "architecture_v12_4.ipynb")
with open(outpath, "w") as f:
    json.dump(nb, f, indent=1)

print(f"Created {outpath} with {len(cells)} cells")
import ast
errs = 0
for i, c in enumerate(cells):
    if c['cell_type'] == 'code':
        try: ast.parse(''.join(c['source']))
        except SyntaxError as e:
            print(f"SYNTAX ERROR cell {i}: {e}"); errs += 1
if errs == 0:
    print(f"All {sum(1 for c in cells if c['cell_type']=='code')} code cells parse OK")
