"""Generate architecture_v12_2.ipynb with proper cell formatting."""
import json
import os

cells = []

def md(source):
    lines = source.split("\n")
    source_list = [line + "\n" for line in lines[:-1]] + [lines[-1]]
    cells.append({"cell_type": "markdown", "metadata": {}, "source": source_list})

def code(source):
    lines = source.split("\n")
    source_list = [line + "\n" for line in lines[:-1]] + [lines[-1]]
    cells.append({"cell_type": "code", "metadata": {}, "source": source_list,
                  "outputs": [], "execution_count": None})


# ═══════════════════════════════════════════════════════════════
# CELL 0: Title
# ═══════════════════════════════════════════════════════════════
md(
"# V12.2: Spectral Fixes \u2014 Making the Fourier Machinery Work\n"
"\n"
"## Motivation: V12.1 Ablation Exposed Dead Spectral Components\n"
"\n"
"The V12.1 SSM ablation (3000 steps) revealed that the spectral machinery\n"
"contributed **zero measurable value**:\n"
"\n"
"| Model | Params | Val BPC | Val Acc | ms/step |\n"
"|-------|--------|---------|---------|--------|\n"
"| A: Full V12.1 | 2,345,031 | 2.302 | 53.3% | 317 |\n"
"| B: Zero SSM Context | 2,345,031 | 3.589 | 27.0% | 279 |\n"
"| **C: SSM+MLP Only** | **2,112,327** | **2.267** | **53.8%** | **68** |\n"
"| D: No Sparsity | 2,345,031 | 2.275 | 53.4% | 279 |\n"
"\n"
"SSM+MLP alone matched the full architecture at 4.7x the speed. Root cause analysis\n"
"found three bugs preventing the spectral domain from contributing.\n"
"\n"
"## V12.2 Fixes\n"
"\n"
"| Fix | V12.1 (Broken) | V12.2 (Fixed) | Why |\n"
"|-----|----------------|---------------|-----|\n"
"| FFT basis | `fft/ifft` (256 complex, conjugate-redundant) | `rfft/irfft` (136 unique modes) | After block 1, FFT of real\u2192symmetric spectrum. Top-k selects conjugate pairs, halving effective DoF from 10 to ~5. |\n"
"| Transport diffusion | `softplus` (D\u22650, can only dampen) | `tanh` (range [-1,1], can amplify) | Transport could never create spectral energy. Just an expensive low-pass filter. |\n"
"| Settler proximal | Every Langevin step | After final step only | Proximal projected settler state back to sparse manifold at each step, destroying Hopfield gradient progress. |\n"
"\n"
"## Literature Justifications\n"
"\n"
"- **Donoho-Stark 1989**: Uncertainty principle guarantees spectral sparsity \u2192 automatic spatial coverage.\n"
"- **Ramsauer 2021**: Modern Hopfield = softmax attention. Freed proximal lets settler reach attractors.\n"
"- **Santos 2024**: Sparse Hopfield gives exact retrieval with exponential capacity.\n"
"- **Li 2026 (DMHN)**: Context dynamically reshapes attractor manifold \u2014 validates context-dependent transport.\n"
"- **Shi 2025**: Reaction-diffusion framework. Signed diffusion enables bidirectional spectral energy flow.\n"
"- **Hoang 2020**: GNNs are low-pass filters. Transport with only dampening = same pathology.\n"
"- **Candes 2006**: Compressed sensing: s-sparse signal recoverable from O(s log d) independent measurements.\n"
"\n"
"## Non-Negotiables (Preserved)\n"
"\n"
"1. Sparse in spectral, dense only transiently in spatial\n"
"2. Field reconstruction IS the irfft\n"
"3. Langevin starts from the reconstructed (irfft) field\n"
"4. Context warps the spectral metric (D, A context-dependent)\n"
"5. Spectral proximal enforced (after settling completes)\n"
"6. Subbundles are independent spectral channels\n"
"7. No pairwise token attention"
)

# ═══════════════════════════════════════════════════════════════
# CELL 1: Imports + Data
# ═══════════════════════════════════════════════════════════════
code(
"import torch\n"
"import torch.nn as nn\n"
"import torch.nn.functional as F\n"
"import numpy as np\n"
"import matplotlib.pyplot as plt\n"
"from dataclasses import dataclass\n"
"import math\n"
"import time\n"
"import os\n"
"\n"
"# Device\n"
"if torch.cuda.is_available():\n"
"    device = torch.device(\"cuda\")\n"
"elif hasattr(torch.backends, \"mps\") and torch.backends.mps.is_available():\n"
"    device = torch.device(\"mps\")\n"
"else:\n"
"    device = torch.device(\"cpu\")\n"
"print(f\"Device: {device}\")\n"
"\n"
"# Data\n"
"DATA_URL = \"https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt\"\n"
"DATA_PATH = os.path.join(os.getcwd(), \"tiny_shakespeare.txt\")\n"
"\n"
"if not os.path.exists(DATA_PATH):\n"
"    print(\"Downloading Tiny Shakespeare...\")\n"
"    import urllib.request\n"
"    urllib.request.urlretrieve(DATA_URL, DATA_PATH)\n"
"\n"
"with open(DATA_PATH, \"r\") as f:\n"
"    text = f.read()\n"
"\n"
"chars = sorted(set(text))\n"
"vocab_size = len(chars)\n"
"stoi = {c: i for i, c in enumerate(chars)}\n"
"itos = {i: c for c, i in stoi.items()}\n"
"\n"
"data = torch.tensor([stoi[c] for c in text], dtype=torch.long)\n"
"split = int(0.9 * len(data))\n"
"train_data = data[:split]\n"
"val_data = data[split:]\n"
"\n"
"print(f\"Tiny Shakespeare: {len(data):,} chars, vocab {vocab_size}\")\n"
"print(f\"Train: {len(train_data):,} | Val: {len(val_data):,}\")"
)

# ═══════════════════════════════════════════════════════════════
# CELL 2: Config
# ═══════════════════════════════════════════════════════════════
code(
"@dataclass\n"
"class V12_2Config:\n"
"    # Fiber geometry\n"
"    fiber_dim: int = 256\n"
"    n_subbundles: int = 8\n"
"    spectral_sparsity: int = 10      # active modes per subbundle (of 17 unique)\n"
"\n"
"    # Vocabulary\n"
"    vocab_size: int = 65\n"
"    max_seq_len: int = 128\n"
"\n"
"    # Architecture\n"
"    n_blocks: int = 6\n"
"    context_dim: int = 128\n"
"    atoms_per_subbundle: int = 16\n"
"    mlp_ratio: float = 1.5           # MLP hidden = fiber_dim * mlp_ratio = 384\n"
"\n"
"    # Langevin settling\n"
"    langevin_steps: int = 2\n"
"    langevin_lr: float = 0.03\n"
"    beta_init: float = 4.0\n"
"    beta_final: float = 12.0\n"
"\n"
"    # Training -- trapezoidal LR: warmup -> hold at peak -> cosine decay\n"
"    learning_rate: float = 3e-3\n"
"    min_lr: float = 3e-4\n"
"    warmup_steps: int = 750\n"
"    lr_hold_steps: int = 3250        # hold at peak LR until step 4000\n"
"    dropout: float = 0.1\n"
"    batch_size: int = 32\n"
"    seq_len: int = 128\n"
"    max_steps: int = 10000\n"
"    eval_interval: int = 500\n"
"    eval_steps: int = 10\n"
"\n"
"    @property\n"
"    def subbundle_dim(self):\n"
"        return self.fiber_dim // self.n_subbundles   # 32\n"
"\n"
"    @property\n"
"    def spectral_half_dim(self):\n"
"        \"\"\"Unique spectral modes per subbundle (DC through Nyquist).\n"
"        For subbundle_dim=32: 17 unique modes.\"\"\"\n"
"        return self.subbundle_dim // 2 + 1\n"
"\n"
"    @property\n"
"    def spectral_dim(self):\n"
"        \"\"\"Total unique spectral dimension across all subbundles.\n"
"        8 subbundles x 17 modes = 136.\"\"\"\n"
"        return self.n_subbundles * self.spectral_half_dim\n"
"\n"
"    @property\n"
"    def total_active_modes(self):\n"
"        return self.n_subbundles * self.spectral_sparsity\n"
"\n"
"    @property\n"
"    def mlp_hidden(self):\n"
"        return int(self.fiber_dim * self.mlp_ratio)\n"
"\n"
"\n"
"config = V12_2Config(vocab_size=vocab_size)\n"
"print(f\"Fiber: {config.fiber_dim} = {config.n_subbundles} x {config.subbundle_dim}\")\n"
"print(f\"Spectral: {config.spectral_dim} = {config.n_subbundles} x {config.spectral_half_dim} (unique half-spectrum)\")\n"
"print(f\"Spectral sparsity: {config.spectral_sparsity}/{config.spectral_half_dim} modes per subbundle \"\n"
"      f\"= {100*config.spectral_sparsity/config.spectral_half_dim:.0f}% active \"\n"
"      f\"({config.total_active_modes}/{config.spectral_dim} total)\")\n"
"print(f\"Blocks: {config.n_blocks}, Context dim: {config.context_dim}\")\n"
"print(f\"MLP hidden: {config.mlp_hidden}\")\n"
"print(f\"Langevin steps: {config.langevin_steps}, beta: {config.beta_init} -> {config.beta_final}\")\n"
"print(f\"Atoms: {config.atoms_per_subbundle} per subbundle\")\n"
"decay_start = config.warmup_steps + config.lr_hold_steps\n"
"print(f\"LR: warmup 0->{config.learning_rate} (0-{config.warmup_steps}), \"\n"
"      f\"hold ({config.warmup_steps}-{decay_start}), \"\n"
"      f\"cosine -> {config.min_lr} ({decay_start}-{config.max_steps})\")\n"
"\n"
"def get_batch(split_data, cfg):\n"
"    max_start = len(split_data) - cfg.seq_len - 1\n"
"    starts = torch.randint(0, max_start, (cfg.batch_size,))\n"
"    return torch.stack([split_data[s:s+cfg.seq_len] for s in starts]).to(device)"
)

# ═══════════════════════════════════════════════════════════════
# CELL 3: Architecture header
# ═══════════════════════════════════════════════════════════════
md(
"## V12.2 Architecture Modules\n"
"\n"
"Three targeted spectral fixes from the V12.1 ablation diagnosis:\n"
"1. **rfft/irfft** \u2014 eliminates conjugate redundancy, 10 selected = 10 independent DoF\n"
"2. **Signed diffusion** \u2014 transport can amplify or dampen modes (tanh, not softplus)\n"
"3. **Proximal at end** \u2014 settler explores freely, projects to sparse manifold once"
)

# ═══════════════════════════════════════════════════════════════
# CELL 4-10: Architecture modules - read from v12_1.py (already fixed)
# ═══════════════════════════════════════════════════════════════

# Read the fixed v12_1.py to extract module code
v12_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "v12_1.py")
with open(v12_path) as f:
    v12_src = f.read()

# Cell 4: Utilities
code(
"# -- Shared utilities (rfft/irfft fixes) ------------------------------------\n"
"\n"
"def spectral_sparsify(x_complex, cfg):\n"
"    \"\"\"Per-subbundle top-s_k sparsification in half-spectrum (rfft domain).\n"
"    Each selected mode is an independent spectral degree of freedom --\n"
"    no conjugate redundancy. Uses pairwise comparison (MPS-friendly).\"\"\"\n"
"    shape = x_complex.shape\n"
"    x_subs = x_complex.reshape(*shape[:-1], cfg.n_subbundles, cfg.spectral_half_dim)\n"
"    with torch.no_grad():\n"
"        mags = x_subs.abs()\n"
"        gt_count = (mags.unsqueeze(-1) < mags.unsqueeze(-2)).sum(dim=-1)\n"
"        mask = (gt_count < cfg.spectral_sparsity).float()\n"
"    return (x_subs * mask).reshape(shape)\n"
"\n"
"\n"
"def spectral_to_spatial(x_spectral, cfg):\n"
"    \"\"\"irfft per subbundle: unique half-spectrum -> dense spatial (real).\n"
"    No .real needed -- irfft returns real by construction.\"\"\"\n"
"    shape = x_spectral.shape[:-1]\n"
"    subs = x_spectral.reshape(*shape, cfg.n_subbundles, cfg.spectral_half_dim)\n"
"    spatial = torch.fft.irfft(subs, n=cfg.subbundle_dim, dim=-1)\n"
"    return spatial.reshape(*shape, cfg.fiber_dim)\n"
"\n"
"\n"
"def spatial_to_spectral(x_spatial, cfg):\n"
"    \"\"\"rfft per subbundle: dense spatial -> unique half-spectrum (complex).\n"
"    Only stores modes 0..N/2 -- each mode is independent.\"\"\"\n"
"    shape = x_spatial.shape[:-1]\n"
"    subs = x_spatial.reshape(*shape, cfg.n_subbundles, cfg.subbundle_dim)\n"
"    spectral = torch.fft.rfft(subs, dim=-1)\n"
"    return spectral.reshape(*shape, cfg.spectral_dim)\n"
"\n"
"\n"
"def spectral_proximal(x_spatial, cfg):\n"
"    \"\"\"Proximal operator: rfft -> top-s_k per subbundle -> irfft.\n"
"    Enforces spectral sparsity while operating on spatial state.\"\"\"\n"
"    x_spec = spatial_to_spectral(x_spatial, cfg)\n"
"    x_sparse = spectral_sparsify(x_spec, cfg)\n"
"    return spectral_to_spatial(x_sparse, cfg)\n"
"\n"
"\n"
"def parallel_associative_scan(A, B):\n"
"    \"\"\"O(log T) Hillis-Steele parallel scan: q_t = A_t * q_{t-1} + B_t.\"\"\"\n"
"    _, T, _ = A.shape\n"
"    a, b = A, B\n"
"    for d in range(int(math.ceil(math.log2(T)))):\n"
"        step = 2 ** d\n"
"        if step >= T:\n"
"            break\n"
"        b = torch.cat([b[:, :step, :],\n"
"                        a[:, step:, :] * b[:, :-step, :] + b[:, step:, :]], dim=1)\n"
"        a = torch.cat([a[:, :step, :],\n"
"                        a[:, step:, :] * a[:, :-step, :]], dim=1)\n"
"    return b\n"
"\n"
"\n"
"# -- Verify rfft/irfft round-trip --\n"
"_test = torch.randn(2, 128, 256)\n"
"_spec = spatial_to_spectral(_test, config)\n"
"_back = spectral_to_spatial(_spec, config)\n"
"_err = (_test - _back).abs().max().item()\n"
"print(f\"Utilities defined (rfft/irfft)\")\n"
"print(f\"  rfft round-trip error: {_err:.2e} (should be ~1e-7)\")\n"
"print(f\"  spectral dim: {_spec.shape[-1]} (136 = 8 x 17 unique modes)\")\n"
"_sparse = spectral_sparsify(_spec, config)\n"
"_active = (_sparse.abs() > 1e-8).float().mean().item()\n"
"print(f\"  sparsity: {_active:.1%} active ({config.spectral_sparsity}/{config.spectral_half_dim} per subbundle)\")"
)

# Cell 5: SpectralTokenEmbedding
code(
"# -- Spectral Token Embedding (half-spectrum) --------------------------------\n"
"\n"
"class SpectralTokenEmbedding(nn.Module):\n"
"    \"\"\"Tokens as sparse spectral configurations (half-spectrum).\n"
"    Magnitude embedding + learned phase + positional phase -> complex spectral -> sparsify.\n"
"    Uses rfft frequencies: each mode is an independent spectral DoF.\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.mag_embedding = nn.Embedding(cfg.vocab_size, cfg.spectral_dim)\n"
"        self.phase_embedding = nn.Embedding(cfg.vocab_size, cfg.spectral_dim)\n"
"        nn.init.uniform_(self.phase_embedding.weight, -math.pi, math.pi)\n"
"\n"
"        freqs = torch.zeros(cfg.spectral_dim)\n"
"        for k in range(cfg.n_subbundles):\n"
"            offset = k * cfg.spectral_half_dim\n"
"            freqs[offset:offset + cfg.spectral_half_dim] = (\n"
"                2 * math.pi * torch.fft.rfftfreq(cfg.subbundle_dim, d=1.0)\n"
"            )\n"
"        self.register_buffer(\"freqs\", freqs)\n"
"\n"
"    def forward(self, token_ids):\n"
"        B, T = token_ids.shape\n"
"        mag = self.mag_embedding(token_ids)\n"
"        phase_offset = self.phase_embedding(token_ids)\n"
"        positions = torch.arange(T, device=token_ids.device).float()\n"
"        pos_phase = positions.unsqueeze(-1) * self.freqs.unsqueeze(0)\n"
"        total_phase = phase_offset + pos_phase.unsqueeze(0)\n"
"        spectral = mag * torch.exp(1j * total_phase)\n"
"        return spectral_sparsify(spectral, self.cfg)"
)

# Cell 6: ContextAccumulator
code(
"# -- Context Accumulator (SSM) -----------------------------------------------\n"
"\n"
"class ContextAccumulator(nn.Module):\n"
"    \"\"\"Content-dependent SSM with parallel scan.\n"
"    q_t = A(x_t) * q_{t-1} + B(x_t) * psi(x_t)\n"
"    fiber_dim -> context_dim (128).\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.A_proj = nn.Linear(cfg.fiber_dim, cfg.context_dim)\n"
"        self.B_proj = nn.Linear(cfg.fiber_dim, cfg.context_dim)\n"
"        self.psi_proj = nn.Linear(cfg.fiber_dim, cfg.context_dim)\n"
"\n"
"    def forward(self, x_spatial):\n"
"        A = torch.sigmoid(self.A_proj(x_spatial))\n"
"        B = torch.sigmoid(self.B_proj(x_spatial))\n"
"        psi = self.psi_proj(x_spatial)\n"
"        return parallel_associative_scan(A, B * psi)"
)

# Cell 7: SpectralTransport
code(
"# -- Spectral Transport (FIX: signed diffusion) -----------------------------\n"
"\n"
"class SpectralTransport(nn.Module):\n"
"    \"\"\"Context-dependent spectral transport kernel (half-spectrum).\n"
"    X_tilde(w) = X(w) * exp(-D(ctx)*w^2 - i*w*A(ctx))\n"
"\n"
"    FIX: Signed diffusion via tanh (range [-1, 1]).\n"
"    - D > 0: damping (low-pass, attenuate high freq)\n"
"    - D < 0: amplification (high-pass, boost high freq)\n"
"    V12.1 used softplus (D >= 0), so transport could ONLY dampen.\n"
"\n"
"    Projects context_dim -> spectral_dim (136, not fiber_dim 256).\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.D_proj = nn.Linear(cfg.context_dim, cfg.spectral_dim)\n"
"        self.A_proj = nn.Linear(cfg.context_dim, cfg.spectral_dim)\n"
"\n"
"    def forward(self, spectral_x, q_t):\n"
"        cfg = self.cfg\n"
"        diffusion = torch.tanh(self.D_proj(q_t)) * 1.0\n"
"        gauge = self.A_proj(q_t)\n"
"\n"
"        freqs = torch.fft.rfftfreq(cfg.subbundle_dim, d=1.0, device=spectral_x.device)\n"
"        freqs = freqs.repeat(cfg.n_subbundles)\n"
"        w2 = freqs ** 2\n"
"        w = freqs\n"
"\n"
"        kernel = torch.exp(-diffusion * w2 - 1j * w * gauge)\n"
"        return spectral_x * kernel"
)

# Cell 8: SimplifiedMemoryBank
code(
"# -- Simplified Memory Bank (FIX: half-spectrum atoms) -----------------------\n"
"\n"
"class SimplifiedMemoryBank(nn.Module):\n"
"    \"\"\"Memory atoms with direct dot-product Hopfield routing.\n"
"    Atoms stored as half-spectrum (real, imag), irfft'd to spatial for comparison.\n"
"    Ramsauer 2021: this IS modern Hopfield retrieval.\n"
"    Santos 2024: sparse Hopfield gives exact retrieval.\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        shd = cfg.spectral_half_dim\n"
"        K = cfg.n_subbundles\n"
"        A = cfg.atoms_per_subbundle\n"
"\n"
"        self.dict_real = nn.ParameterList([\n"
"            nn.Parameter(torch.randn(A, shd) * 0.02) for _ in range(K)\n"
"        ])\n"
"        self.dict_imag = nn.ParameterList([\n"
"            nn.Parameter(torch.randn(A, shd) * 0.02) for _ in range(K)\n"
"        ])\n"
"\n"
"    def get_spatial_atoms(self):\n"
"        \"\"\"irfft: half-spectrum -> real spatial (no .real needed).\"\"\"\n"
"        cfg = self.cfg\n"
"        all_real = torch.stack(list(self.dict_real))\n"
"        all_imag = torch.stack(list(self.dict_imag))\n"
"        all_spatial = F.normalize(\n"
"            torch.fft.irfft(torch.complex(all_real, all_imag),\n"
"                            n=cfg.subbundle_dim, dim=-1),\n"
"            dim=-1\n"
"        )\n"
"        return all_spatial"
)

# Cell 9: SpectralHopfieldSettler
code(
"# -- Spectral Hopfield Settler (FIX: proximal at end only) -------------------\n"
"\n"
"class SpectralHopfieldSettler(nn.Module):\n"
"    \"\"\"2-step Langevin settling with spectral proximal AFTER final step.\n"
"\n"
"    FIX: V12.1 applied proximal at each Langevin step, projecting state back\n"
"    to sparse spectral manifold and destroying Hopfield gradient progress.\n"
"    Now settler explores freely, projects once at the end.\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.W_inh = nn.Parameter(torch.ones(cfg.fiber_dim) * 0.01)\n"
"\n"
"    def forward(self, dense_field, spatial_atoms):\n"
"        cfg = self.cfg\n"
"        B, T, D = dense_field.shape\n"
"        sd = cfg.subbundle_dim\n"
"        K = cfg.n_subbundles\n"
"        BT = B * T\n"
"\n"
"        x = dense_field\n"
"        betas = torch.linspace(cfg.beta_init, cfg.beta_final, cfg.langevin_steps,\n"
"                               device=dense_field.device)\n"
"        M_all = spatial_atoms.unsqueeze(0).expand(BT, -1, -1, -1)\n"
"\n"
"        for step in range(cfg.langevin_steps):\n"
"            beta = betas[step].item()\n"
"            x_subs = x.reshape(BT, K, sd)\n"
"            sim = torch.einsum('bks,bkas->bka', x_subs, M_all)\n"
"            w = F.softmax(beta * sim, dim=-1)\n"
"            grad_E = -torch.einsum('bka,bkas->bks', w, M_all)\n"
"            inhib = self.W_inh * x\n"
"            x = x - cfg.langevin_lr * (grad_E.reshape(B, T, D) + inhib)\n"
"            if not self.training:\n"
"                x = x + math.sqrt(2.0 * cfg.langevin_lr / beta) * torch.randn_like(x)\n"
"\n"
"        # Spectral proximal ONLY after final step\n"
"        x = spectral_proximal(x, cfg)\n"
"        return x"
)

# Cell 10: SpatialMLP
code(
"# -- Spatial MLP -------------------------------------------------------------\n"
"\n"
"class SpatialMLP(nn.Module):\n"
"    \"\"\"Nonlinear channel mixing in spatial domain (Shi 2025: 'reaction' term).\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.fc1 = nn.Linear(cfg.fiber_dim, cfg.mlp_hidden)\n"
"        self.fc2 = nn.Linear(cfg.mlp_hidden, cfg.fiber_dim)\n"
"        self.drop = nn.Dropout(cfg.dropout)\n"
"\n"
"    def forward(self, x):\n"
"        return self.drop(self.fc2(F.silu(self.fc1(x))))"
)

# Cell 11: V12_2Block
code(
"# -- V12.2 Block -------------------------------------------------------------\n"
"\n"
"class V12_2Block(nn.Module):\n"
"    \"\"\"One forward-reverse spectral diffusion cycle + spatial MLP.\n"
"\n"
"    Flow:\n"
"    spectral (136 complex) -> irfft -> SSM context -> spectral transport ->\n"
"    irfft (field reconstruction) -> 2-step Hopfield settling (free exploration) ->\n"
"    spectral proximal (once) -> SpatialMLP (residual delta) ->\n"
"    rfft + re-sparsify -> spectral out (136 complex)\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.context_acc = ContextAccumulator(cfg)\n"
"        self.transport = SpectralTransport(cfg)\n"
"        self.memory = SimplifiedMemoryBank(cfg)\n"
"        self.settler = SpectralHopfieldSettler(cfg)\n"
"        self.mlp = SpatialMLP(cfg)\n"
"        self.norm1 = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.norm2 = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.res_gate = nn.Parameter(torch.tensor(0.5))\n"
"        self.dropout = nn.Dropout(cfg.dropout)\n"
"\n"
"    def forward(self, spectral_x):\n"
"        cfg = self.cfg\n"
"\n"
"        # 1. Spatial projection for context accumulation\n"
"        x_spatial_in = spectral_to_spatial(spectral_x, cfg)\n"
"\n"
"        # 2. Context accumulator (SSM on spatial)\n"
"        q_t = self.context_acc(x_spatial_in)\n"
"\n"
"        # 3. Spectral transport (context-dependent, signed diffusion)\n"
"        transported = self.transport(spectral_x, q_t)\n"
"\n"
"        # 4. Field reconstruction: irfft -> dense spatial\n"
"        dense_field = spectral_to_spatial(transported, cfg)\n"
"        dense_field = self.norm1(dense_field)\n"
"\n"
"        # 5. Hopfield settling (free exploration + proximal at end)\n"
"        spatial_atoms = self.memory.get_spatial_atoms()\n"
"        settled = self.settler(dense_field, spatial_atoms)\n"
"\n"
"        # 6. Spatial MLP (nonlinear channel mixing)\n"
"        mlp_out = self.mlp(self.norm2(settled))\n"
"\n"
"        # 7. Gated residual in spatial domain\n"
"        gate = torch.sigmoid(self.res_gate)\n"
"        x_spatial_out = x_spatial_in + gate * self.dropout(mlp_out)\n"
"\n"
"        # 8. Back to spectral and enforce sparsity\n"
"        spectral_out = spatial_to_spectral(x_spatial_out, cfg)\n"
"        spectral_out = spectral_sparsify(spectral_out, cfg)\n"
"\n"
"        return spectral_out"
)

# Cell 12: Full Model + GPT + SSM + instantiate
code(
"# -- Full V12.2 Model --------------------------------------------------------\n"
"\n"
"class V12_2Model(nn.Module):\n"
"    \"\"\"V12.2: Fixed Spectral Sparsity CLM.\n"
"    Selective deep supervision at blocks 2, 4, 6 (every other).\"\"\"\n"
"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.embedding = SpectralTokenEmbedding(cfg)\n"
"        self.blocks = nn.ModuleList([V12_2Block(cfg) for _ in range(cfg.n_blocks)])\n"
"        self.final_norm = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.decoder = nn.Sequential(\n"
"            nn.Linear(cfg.fiber_dim, cfg.fiber_dim), nn.SiLU(),\n"
"            nn.Dropout(cfg.dropout),\n"
"            nn.Linear(cfg.fiber_dim, cfg.vocab_size),\n"
"        )\n"
"        weights = torch.zeros(cfg.n_blocks)\n"
"        for i in range(cfg.n_blocks):\n"
"            if (i + 1) % 2 == 0:\n"
"                weights[i] = (i + 1) / cfg.n_blocks\n"
"        weights[-1] = 1.0\n"
"        self.register_buffer(\"block_loss_weights\", weights)\n"
"\n"
"    def _decode_spatial(self, spectral_x):\n"
"        spatial = spectral_to_spatial(spectral_x, self.cfg)\n"
"        return self.decoder(self.final_norm(spatial))\n"
"\n"
"    def forward(self, token_ids):\n"
"        B, T = token_ids.shape\n"
"        cfg = self.cfg\n"
"        spectral_x = self.embedding(token_ids)\n"
"        intermediate_logits = []\n"
"        for i, block in enumerate(self.blocks):\n"
"            spectral_x = block(spectral_x)\n"
"            if self.block_loss_weights[i] > 0:\n"
"                logits = self._decode_spatial(spectral_x)[:, :-1, :]\n"
"                intermediate_logits.append((logits, self.block_loss_weights[i]))\n"
"        spatial_final = spectral_to_spatial(spectral_x, cfg)\n"
"        spec_check = spatial_to_spectral(spatial_final, cfg)\n"
"        spec_sparsity = (spec_check.abs() < 1e-6).float().mean().item()\n"
"        final_logits = intermediate_logits[-1][0]\n"
"        info = {\"spectral_sparsity\": spec_sparsity, \"intermediate_logits\": intermediate_logits}\n"
"        return final_logits, info\n"
"\n"
"\n"
"# -- GPT-Nano Baseline -------------------------------------------------------\n"
"\n"
"class GPTNano(nn.Module):\n"
"    def __init__(self, vocab_size=65, n_embd=128, n_head=4, n_layer=12,\n"
"                 block_size=128, dropout=0.1):\n"
"        super().__init__()\n"
"        self.block_size = block_size\n"
"        self.tok_emb = nn.Embedding(vocab_size, n_embd)\n"
"        self.pos_emb = nn.Embedding(block_size, n_embd)\n"
"        self.drop = nn.Dropout(dropout)\n"
"        self.blocks = nn.ModuleList()\n"
"        for _ in range(n_layer):\n"
"            self.blocks.append(nn.ModuleDict({\n"
"                'ln1': nn.LayerNorm(n_embd),\n"
"                'attn_qkv': nn.Linear(n_embd, 3 * n_embd),\n"
"                'attn_proj': nn.Linear(n_embd, n_embd),\n"
"                'ln2': nn.LayerNorm(n_embd),\n"
"                'mlp_fc1': nn.Linear(n_embd, 4 * n_embd),\n"
"                'mlp_fc2': nn.Linear(4 * n_embd, n_embd),\n"
"            }))\n"
"        self.ln_f = nn.LayerNorm(n_embd)\n"
"        self.lm_head = nn.Linear(n_embd, vocab_size, bias=False)\n"
"        self.n_head = n_head\n"
"        self.n_embd = n_embd\n"
"        causal_mask = torch.tril(torch.ones(block_size, block_size))\n"
"        self.register_buffer('causal_mask', causal_mask.view(1, 1, block_size, block_size))\n"
"\n"
"    def forward(self, idx):\n"
"        B, T = idx.shape\n"
"        pos = torch.arange(T, device=idx.device)\n"
"        x = self.drop(self.tok_emb(idx) + self.pos_emb(pos))\n"
"        head_dim = self.n_embd // self.n_head\n"
"        for block in self.blocks:\n"
"            h = block['ln1'](x)\n"
"            qkv = block['attn_qkv'](h).reshape(B, T, 3, self.n_head, head_dim)\n"
"            q, k, v = qkv.unbind(2)\n"
"            q, k, v = q.transpose(1, 2), k.transpose(1, 2), v.transpose(1, 2)\n"
"            att = (q @ k.transpose(-2, -1)) * (head_dim ** -0.5)\n"
"            att = att.masked_fill(self.causal_mask[:, :, :T, :T] == 0, float('-inf'))\n"
"            att = F.softmax(att, dim=-1)\n"
"            y = (att @ v).transpose(1, 2).reshape(B, T, self.n_embd)\n"
"            x = x + block['attn_proj'](y)\n"
"            h = block['ln2'](x)\n"
"            x = x + block['mlp_fc2'](F.gelu(block['mlp_fc1'](h)))\n"
"        logits = self.lm_head(self.ln_f(x))\n"
"        return logits[:, :-1, :], {}\n"
"\n"
"\n"
"# -- SSM+MLP Only (ablation baseline) ----------------------------------------\n"
"\n"
"class SSMOnlyBlock(nn.Module):\n"
"    \"\"\"Pure spatial: SSM context -> MLP -> gated residual. No spectral domain.\"\"\"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.context_acc = ContextAccumulator(cfg)\n"
"        self.ctx_proj = nn.Linear(cfg.context_dim, cfg.fiber_dim)\n"
"        self.mlp = SpatialMLP(cfg)\n"
"        self.norm1 = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.norm2 = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.res_gate = nn.Parameter(torch.tensor(0.5))\n"
"        self.dropout = nn.Dropout(cfg.dropout)\n"
"\n"
"    def forward(self, x):\n"
"        q_t = self.context_acc(x)\n"
"        ctx_out = self.ctx_proj(q_t)\n"
"        h = self.norm1(x + ctx_out)\n"
"        mlp_out = self.mlp(self.norm2(h))\n"
"        gate = torch.sigmoid(self.res_gate)\n"
"        return x + gate * self.dropout(ctx_out + mlp_out)\n"
"\n"
"\n"
"class SSMOnlyModel(nn.Module):\n"
"    \"\"\"SSM + MLP only -- no spectral domain, no Hopfield.\"\"\"\n"
"    def __init__(self, cfg):\n"
"        super().__init__()\n"
"        self.cfg = cfg\n"
"        self.embedding = nn.Embedding(cfg.vocab_size, cfg.fiber_dim)\n"
"        self.pos_embedding = nn.Embedding(cfg.max_seq_len, cfg.fiber_dim)\n"
"        self.drop = nn.Dropout(cfg.dropout)\n"
"        self.blocks = nn.ModuleList([SSMOnlyBlock(cfg) for _ in range(cfg.n_blocks)])\n"
"        self.final_norm = nn.LayerNorm(cfg.fiber_dim)\n"
"        self.decoder = nn.Sequential(\n"
"            nn.Linear(cfg.fiber_dim, cfg.fiber_dim), nn.SiLU(),\n"
"            nn.Dropout(cfg.dropout),\n"
"            nn.Linear(cfg.fiber_dim, cfg.vocab_size),\n"
"        )\n"
"\n"
"    def forward(self, token_ids):\n"
"        B, T = token_ids.shape\n"
"        pos = torch.arange(T, device=token_ids.device)\n"
"        x = self.drop(self.embedding(token_ids) + self.pos_embedding(pos))\n"
"        for block in self.blocks:\n"
"            x = block(x)\n"
"        logits = self.decoder(self.final_norm(x))[:, :-1, :]\n"
"        info = {\"spectral_sparsity\": 0.0, \"intermediate_logits\": [(logits, 1.0)]}\n"
"        return logits, info\n"
"\n"
"\n"
"# -- Instantiate and count parameters ----------------------------------------\n"
"model = V12_2Model(config).to(device)\n"
"gpt_model = GPTNano(vocab_size=vocab_size, block_size=config.seq_len).to(device)\n"
"ssm_model = SSMOnlyModel(config).to(device)\n"
"\n"
"def count_params(m):\n"
"    return sum(p.numel() for p in m.parameters())\n"
"\n"
"print(f\"V12.2:       {count_params(model):>10,} params\")\n"
"print(f\"GPT-Nano:    {count_params(gpt_model):>10,} params\")\n"
"print(f\"SSM+MLP:     {count_params(ssm_model):>10,} params\")\n"
"\n"
"# Per-component breakdown for V12.2\n"
"n_embed = sum(p.numel() for p in model.embedding.parameters())\n"
"n_ctx = sum(sum(p.numel() for p in blk.context_acc.parameters()) for blk in model.blocks)\n"
"n_transport = sum(sum(p.numel() for p in blk.transport.parameters()) for blk in model.blocks)\n"
"n_memory = sum(sum(p.numel() for p in blk.memory.parameters()) for blk in model.blocks)\n"
"n_settler = sum(sum(p.numel() for p in blk.settler.parameters()) for blk in model.blocks)\n"
"n_mlp = sum(sum(p.numel() for p in blk.mlp.parameters()) for blk in model.blocks)\n"
"n_decoder = sum(p.numel() for p in model.decoder.parameters()) + \\\n"
"            sum(p.numel() for p in model.final_norm.parameters())\n"
"n_other = count_params(model) - (n_embed + n_ctx + n_transport + n_memory + n_settler + n_mlp + n_decoder)\n"
"\n"
"print(f\"\\nV12.2 Breakdown:\")\n"
"print(f\"  Embedding (spectral): {n_embed:>8,} ({100*n_embed/count_params(model):.1f}%)\")\n"
"print(f\"  SSM context:          {n_ctx:>8,} ({100*n_ctx/count_params(model):.1f}%)\")\n"
"print(f\"  Transport:            {n_transport:>8,} ({100*n_transport/count_params(model):.1f}%)\")\n"
"print(f\"  Memory atoms:         {n_memory:>8,} ({100*n_memory/count_params(model):.1f}%)\")\n"
"print(f\"  Settler:              {n_settler:>8,} ({100*n_settler/count_params(model):.1f}%)\")\n"
"print(f\"  SpatialMLP:           {n_mlp:>8,} ({100*n_mlp/count_params(model):.1f}%)\")\n"
"print(f\"  Decoder + norm:       {n_decoder:>8,} ({100*n_decoder/count_params(model):.1f}%)\")\n"
"print(f\"  Other (gates, norms): {n_other:>8,} ({100*n_other/count_params(model):.1f}%)\")"
)

# Cell 13: Training header
md("## Training")

# Cell 14: Training functions
code(
"@torch.no_grad()\n"
"def estimate_loss(model, cfg, is_gpt=False):\n"
"    model.eval()\n"
"    results = {}\n"
"    for name, sd in [(\"train\", train_data), (\"val\", val_data)]:\n"
"        tot_ce, tot_ok, tot_n, tot_sp = 0., 0, 0, 0.\n"
"        for _ in range(cfg.eval_steps):\n"
"            b = get_batch(sd, cfg)\n"
"            logits, info = model(b)\n"
"            tgt = b[:, 1:]\n"
"            ce = F.cross_entropy(logits.reshape(-1, cfg.vocab_size), tgt.reshape(-1))\n"
"            tot_ce += ce.item()\n"
"            tot_ok += (logits.argmax(-1) == tgt).sum().item()\n"
"            tot_n += tgt.numel()\n"
"            if not is_gpt:\n"
"                tot_sp += info.get(\"spectral_sparsity\", 0.0)\n"
"        n = cfg.eval_steps\n"
"        results[name] = {\n"
"            \"ce\": tot_ce/n, \"acc\": tot_ok/tot_n,\n"
"            \"sparsity\": tot_sp/n if not is_gpt else 0.0,\n"
"        }\n"
"    model.train()\n"
"    return results\n"
"\n"
"\n"
"def train_model(model, cfg, label=\"V12.2\", is_gpt=False, is_ssm_only=False):\n"
"    \"\"\"Train loop for V12.2, GPT, and SSM+MLP models.\"\"\"\n"
"    optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.learning_rate, weight_decay=0.05)\n"
"\n"
"    min_ratio = getattr(cfg, 'min_lr', 0) / cfg.learning_rate\n"
"    hold_end = cfg.warmup_steps + getattr(cfg, 'lr_hold_steps', 0)\n"
"\n"
"    def lr_lambda(step):\n"
"        if step < cfg.warmup_steps:\n"
"            return step / max(1, cfg.warmup_steps)\n"
"        if step < hold_end:\n"
"            return 1.0\n"
"        progress = (step - hold_end) / max(1, cfg.max_steps - hold_end)\n"
"        cosine = 0.5 * (1.0 + math.cos(math.pi * progress))\n"
"        return max(min_ratio, cosine)\n"
"\n"
"    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)\n"
"\n"
"    history = {\n"
"        \"step\": [], \"train_ce\": [], \"val_ce\": [],\n"
"        \"train_acc\": [], \"val_acc\": [],\n"
"        \"train_bpc\": [], \"val_bpc\": [],\n"
"        \"sparsity\": [], \"lr\": [],\n"
"        \"step_times\": [], \"per_step_loss\": [],\n"
"    }\n"
"\n"
"    model.train()\n"
"    total_start = time.time()\n"
"    n_params = count_params(model)\n"
"\n"
"    print(f\"\\nTraining {label}: {n_params:,} params\")\n"
"    print(f\"Steps: {cfg.max_steps}, Batch: {cfg.batch_size}, Seq: {cfg.seq_len}\")\n"
"    print(\"=\" * 70)\n"
"\n"
"    for step in range(cfg.max_steps + 1):\n"
"        if step % cfg.eval_interval == 0:\n"
"            res = estimate_loss(model, cfg, is_gpt=is_gpt)\n"
"            tr, vl = res[\"train\"], res[\"val\"]\n"
"            history[\"step\"].append(step)\n"
"            history[\"train_ce\"].append(tr[\"ce\"])\n"
"            history[\"val_ce\"].append(vl[\"ce\"])\n"
"            history[\"train_acc\"].append(tr[\"acc\"])\n"
"            history[\"val_acc\"].append(vl[\"acc\"])\n"
"            history[\"train_bpc\"].append(tr[\"ce\"] / math.log(2))\n"
"            history[\"val_bpc\"].append(vl[\"ce\"] / math.log(2))\n"
"            history[\"sparsity\"].append(vl[\"sparsity\"])\n"
"            history[\"lr\"].append(scheduler.get_last_lr()[0])\n"
"            sp_str = f\" | Sp: {vl['sparsity']:.1%}\" if not is_gpt else \"\"\n"
"            print(f\"[{label}] Step {step:5d} | Train CE: {tr['ce']:.3f} | \"\n"
"                  f\"Val CE: {vl['ce']:.3f} | Val BPC: {vl['ce']/math.log(2):.3f} | \"\n"
"                  f\"Acc: {vl['acc']:.1%}{sp_str}\")\n"
"\n"
"        if step >= cfg.max_steps:\n"
"            break\n"
"\n"
"        step_start = time.time()\n"
"        batch = get_batch(train_data, cfg)\n"
"        optimizer.zero_grad()\n"
"\n"
"        logits, info = model(batch)\n"
"        targets = batch[:, 1:]\n"
"\n"
"        if is_gpt or is_ssm_only:\n"
"            loss = F.cross_entropy(logits.reshape(-1, cfg.vocab_size), targets.reshape(-1))\n"
"        else:\n"
"            # Deep supervision\n"
"            ce_loss, total_weight = 0., 0.\n"
"            for block_logits, weight in info[\"intermediate_logits\"]:\n"
"                ce_loss += weight * F.cross_entropy(\n"
"                    block_logits.reshape(-1, cfg.vocab_size), targets.reshape(-1))\n"
"                total_weight += weight\n"
"            ce_loss /= total_weight\n"
"            # Dictionary coherence loss\n"
"            dcl, nd = 0., 0\n"
"            if hasattr(model, 'blocks'):\n"
"                for blk in model.blocks:\n"
"                    if hasattr(blk, 'memory'):\n"
"                        for dr, di in zip(blk.memory.dict_real, blk.memory.dict_imag):\n"
"                            atoms = torch.fft.irfft(torch.complex(dr, di),\n"
"                                                     n=cfg.subbundle_dim, dim=-1)\n"
"                            An = F.normalize(atoms, dim=-1)\n"
"                            g = An @ An.T\n"
"                            dcl += (g - torch.eye(g.size(0), device=g.device)).pow(2).mean()\n"
"                            nd += 1\n"
"            dcl = dcl / max(nd, 1)\n"
"            loss = ce_loss + 0.1 * dcl\n"
"\n"
"        loss.backward()\n"
"        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n"
"        optimizer.step()\n"
"        scheduler.step()\n"
"\n"
"        history[\"step_times\"].append(time.time() - step_start)\n"
"        history[\"per_step_loss\"].append(loss.item())\n"
"\n"
"        if step % 500 == 0 and step > 0:\n"
"            avg_ms = np.mean(history[\"step_times\"][-500:]) * 1000\n"
"            print(f\"    avg step time: {avg_ms:.0f}ms\")\n"
"\n"
"    elapsed = time.time() - total_start\n"
"    avg_ms = np.mean(history[\"step_times\"]) * 1000\n"
"    print(f\"\\n{label} DONE in {elapsed/60:.1f}min | Final BPC: {history['val_bpc'][-1]:.3f} | \"\n"
"          f\"Acc: {history['val_acc'][-1]:.1%} | Avg: {avg_ms:.0f}ms/step\")\n"
"    history[\"avg_step_ms\"] = avg_ms\n"
"    history[\"n_params\"] = n_params\n"
"    return history"
)

# Cell 15: Train V12.2
code(
"# -- Train V12.2 --\n"
"v12_history = train_model(model, config, label=\"V12.2\", is_gpt=False)"
)

# Cell 16: GPT header
md(
"## GPT-Nano Baseline\n"
"\n"
"12-layer transformer for matched-param comparison. Same data, batch size, sequence\n"
"length, and training schedule."
)

# Cell 17: Train GPT
code(
"# -- Train GPT-Nano --\n"
"gpt_history = train_model(gpt_model, config, label=\"GPT\", is_gpt=True)"
)

# Cell 18: SSM header
md(
"## SSM+MLP Ablation\n"
"\n"
"The critical comparison: does the spectral machinery now contribute?\n"
"If V12.2 beats SSM+MLP, the fixes worked. If not, the spectral domain\n"
"is genuinely redundant at this scale."
)

# Cell 19: Train SSM
code(
"# -- Train SSM+MLP Only --\n"
"ssm_history = train_model(ssm_model, config, label=\"SSM+MLP\", is_gpt=False, is_ssm_only=True)"
)

# Cell 20: Results header
md("## Results Comparison")

# Cell 21: Comparison plots
code(
"# -- Side-by-side comparison ------------------------------------------------\n"
"\n"
"fig, axes = plt.subplots(3, 3, figsize=(18, 15))\n"
"fig.suptitle('V12.2 vs GPT-Nano vs SSM+MLP -- Character-Level Tiny Shakespeare',\n"
"             fontsize=16, fontweight='bold')\n"
"\n"
"all_histories = [\n"
"    (v12_history, 'V12.2', 'b', 'o'),\n"
"    (gpt_history, 'GPT', 'r', 's'),\n"
"    (ssm_history, 'SSM+MLP', 'g', '^'),\n"
"]\n"
"\n"
"# Row 1: Loss curves\n"
"ax = axes[0, 0]\n"
"for h, label, color, marker in all_histories:\n"
"    ax.plot(h['step'], h['val_ce'], f'{color}-{marker}', label=f'{label} Val', markersize=3)\n"
"    ax.plot(h['step'], h['train_ce'], f'{color}--', alpha=0.4, label=f'{label} Train')\n"
"ax.set_xlabel('Step'); ax.set_ylabel('Cross-Entropy')\n"
"ax.set_title('Cross-Entropy Loss'); ax.legend(fontsize=7); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[0, 1]\n"
"for h, label, color, marker in all_histories:\n"
"    ax.plot(h['step'], h['val_bpc'], f'{color}-{marker}', label=label, markersize=3)\n"
"ax.set_xlabel('Step'); ax.set_ylabel('BPC')\n"
"ax.set_title('Bits Per Character (Val)'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[0, 2]\n"
"for h, label, color, marker in all_histories:\n"
"    ax.plot(h['step'], [a*100 for a in h['val_acc']], f'{color}-{marker}', label=label, markersize=3)\n"
"ax.set_xlabel('Step'); ax.set_ylabel('Accuracy (%)')\n"
"ax.set_title('Val Accuracy'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"# Row 2: Training dynamics\n"
"ax = axes[1, 0]\n"
"window = 100\n"
"for h, label, color, marker in all_histories:\n"
"    if len(h['per_step_loss']) > window:\n"
"        smooth = np.convolve(h['per_step_loss'], np.ones(window)/window, mode='valid')\n"
"        ax.plot(range(len(smooth)), smooth, f'{color}-', label=label, alpha=0.8)\n"
"ax.set_xlabel('Step'); ax.set_ylabel('Loss')\n"
"ax.set_title(f'Per-Step Loss (smoothed {window})'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[1, 1]\n"
"for h, label, color, marker in all_histories:\n"
"    ax.plot(h['step'], h['lr'], f'{color}-', label=label)\n"
"ax.set_xlabel('Step'); ax.set_ylabel('Learning Rate')\n"
"ax.set_title('LR Schedule'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[1, 2]\n"
"if any(s > 0 for s in v12_history['sparsity']):\n"
"    ax.plot(v12_history['step'], [s*100 for s in v12_history['sparsity']], 'b-o', markersize=3)\n"
"    ax.set_xlabel('Step'); ax.set_ylabel('Sparsity (%)')\n"
"    ax.set_title('V12.2 Spectral Sparsity'); ax.grid(True, alpha=0.3)\n"
"else:\n"
"    ax.text(0.5, 0.5, 'No sparsity data', ha='center', va='center', transform=ax.transAxes)\n"
"\n"
"# Row 3: Speed and summary\n"
"ax = axes[2, 0]\n"
"for h, label, color, marker in all_histories:\n"
"    if len(h['step_times']) > window:\n"
"        times = np.convolve([t*1000 for t in h['step_times']], np.ones(window)/window, mode='valid')\n"
"        ax.plot(range(len(times)), times, f'{color}-', label=label, alpha=0.8)\n"
"ax.set_xlabel('Step'); ax.set_ylabel('ms/step')\n"
"ax.set_title('Step Time'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"\n"
"ax = axes[2, 1]\n"
"for h, label, color, marker in all_histories:\n"
"    gap = [t - v for t, v in zip(h['train_bpc'], h['val_bpc'])]\n"
"    ax.plot(h['step'], gap, f'{color}-{marker}', label=label, markersize=3)\n"
"ax.set_xlabel('Step'); ax.set_ylabel('Train - Val BPC')\n"
"ax.set_title('Generalization Gap'); ax.legend(); ax.grid(True, alpha=0.3)\n"
"ax.axhline(y=0, color='k', linestyle=':', alpha=0.3)\n"
"\n"
"ax = axes[2, 2]\n"
"ax.axis('off')\n"
"summary_data = []\n"
"for h, label, _, _ in all_histories:\n"
"    summary_data.append([\n"
"        label,\n"
"        f\"{h['n_params']:,}\",\n"
"        f\"{h['val_bpc'][-1]:.3f}\",\n"
"        f\"{h['val_acc'][-1]:.1%}\",\n"
"        f\"{h['avg_step_ms']:.0f}\",\n"
"    ])\n"
"table = ax.table(\n"
"    cellText=summary_data,\n"
"    colLabels=['Model', 'Params', 'BPC', 'Acc', 'ms/step'],\n"
"    loc='center', cellLoc='center'\n"
")\n"
"table.auto_set_font_size(False)\n"
"table.set_fontsize(11)\n"
"table.scale(1.2, 1.8)\n"
"ax.set_title('Final Results', fontweight='bold', pad=20)\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('v12_2_results.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"# Print comparison\n"
"print(\"\\n\" + \"=\" * 70)\n"
"print(\"RESULTS SUMMARY\")\n"
"print(\"=\" * 70)\n"
"v12_bpc = v12_history['val_bpc'][-1]\n"
"gpt_bpc = gpt_history['val_bpc'][-1]\n"
"ssm_bpc = ssm_history['val_bpc'][-1]\n"
"print(f\"V12.2:    BPC {v12_bpc:.3f} | Acc {v12_history['val_acc'][-1]:.1%} | {v12_history['avg_step_ms']:.0f}ms/step\")\n"
"print(f\"GPT-Nano: BPC {gpt_bpc:.3f} | Acc {gpt_history['val_acc'][-1]:.1%} | {gpt_history['avg_step_ms']:.0f}ms/step\")\n"
"print(f\"SSM+MLP:  BPC {ssm_bpc:.3f} | Acc {ssm_history['val_acc'][-1]:.1%} | {ssm_history['avg_step_ms']:.0f}ms/step\")\n"
"print(f\"\\nSpectral contribution: {ssm_bpc - v12_bpc:+.3f} BPC (V12.2 vs SSM+MLP)\")\n"
"if v12_bpc < ssm_bpc - 0.02:\n"
"    print(\"  -> SPECTRAL MACHINERY CONTRIBUTES! Fixes worked.\")\n"
"elif v12_bpc > ssm_bpc + 0.02:\n"
"    print(\"  -> Spectral machinery still hurts. More investigation needed.\")\n"
"else:\n"
"    print(\"  -> Marginal difference. Spectral machinery is neutral at this scale.\")"
)

# Cell 22: Diagnostics header
md("## Diagnostics")

# Cell 23: Diagnostics
code(
"@torch.no_grad()\n"
"def v12_diagnostics(model, cfg):\n"
"    \"\"\"Diagnostic analysis of V12.2 internals.\"\"\"\n"
"    model.eval()\n"
"    batch = get_batch(val_data, cfg)\n"
"\n"
"    spectral_x = model.embedding(batch)\n"
"    emb_sparsity = (spectral_x.abs() < 1e-6).float().mean().item()\n"
"    print(f\"Embedding spectral sparsity: {emb_sparsity:.1%}\")\n"
"    print(f\"Embedding spectral dim: {spectral_x.shape[-1]} (should be {cfg.spectral_dim})\")\n"
"\n"
"    for i, block in enumerate(model.blocks):\n"
"        spectral_x = block(spectral_x)\n"
"        spatial = spectral_to_spatial(spectral_x, cfg)\n"
"        spec = spatial_to_spectral(spatial, cfg)\n"
"        blk_sparsity = (spec.abs() < 1e-6).float().mean().item()\n"
"        gate = torch.sigmoid(block.res_gate).item()\n"
"\n"
"        spec_subs = spec.reshape(*spec.shape[:-1], cfg.n_subbundles, cfg.spectral_half_dim)\n"
"        active = (spec_subs.abs() > 1e-6).float()\n"
"        mode_activity = active.mean(dim=(0, 1))\n"
"        active_modes_per_sub = mode_activity.sum(dim=-1)\n"
"        diversity = mode_activity.std(dim=-1).mean().item()\n"
"\n"
"        spatial_norm = spatial.norm(dim=-1).mean().item()\n"
"        spec_mag = spec.abs().mean().item()\n"
"        print(f\"Block {i+1}: sparsity={blk_sparsity:.1%}, gate={gate:.3f}, \"\n"
"              f\"norm={spatial_norm:.2f}, spec_mag={spec_mag:.4f}, \"\n"
"              f\"mode_div={diversity:.3f}, \"\n"
"              f\"active/sub=[{', '.join(f'{a:.0f}' for a in active_modes_per_sub)}]\")\n"
"\n"
"    print(\"\\nDictionary coherence (lower = more orthogonal):\")\n"
"    for i, blk in enumerate(model.blocks):\n"
"        dcl = 0.\n"
"        for dr, di in zip(blk.memory.dict_real, blk.memory.dict_imag):\n"
"            atoms = torch.fft.irfft(torch.complex(dr, di), n=cfg.subbundle_dim, dim=-1)\n"
"            An = F.normalize(atoms, dim=-1)\n"
"            g = An @ An.T\n"
"            dcl += (g - torch.eye(g.size(0), device=g.device)).pow(2).mean().item()\n"
"        dcl /= cfg.n_subbundles\n"
"        print(f\"  Block {i+1}: DCL = {dcl:.4f}\")\n"
"\n"
"    print(\"\\nTransport kernel statistics:\")\n"
"    spectral_x = model.embedding(batch)\n"
"    for i, block in enumerate(model.blocks):\n"
"        x_spatial = spectral_to_spatial(spectral_x, cfg)\n"
"        q_t = block.context_acc(x_spatial)\n"
"        D = torch.tanh(block.transport.D_proj(q_t)) * 1.0\n"
"        A = block.transport.A_proj(q_t)\n"
"        print(f\"  Block {i+1}: D mean={D.mean():.3f} std={D.std():.3f} \"\n"
"              f\"(neg={100*(D<0).float().mean():.0f}%), \"\n"
"              f\"A mean={A.mean():.3f} std={A.std():.3f}\")\n"
"        spectral_x = block(spectral_x)\n"
"\n"
"    model.train()\n"
"\n"
"v12_diagnostics(model, config)"
)

# Cell 24: Text generation
code(
"@torch.no_grad()\n"
"def generate_text(model, prompt, cfg, max_new=200, temperature=0.8, is_gpt=False):\n"
"    model.eval()\n"
"    ids = torch.tensor([stoi[c] for c in prompt], dtype=torch.long, device=device).unsqueeze(0)\n"
"    for _ in range(max_new):\n"
"        ctx = ids[:, -cfg.seq_len:]\n"
"        logits, _ = model(ctx)\n"
"        logits = logits[:, -1, :] / temperature\n"
"        probs = F.softmax(logits, dim=-1)\n"
"        next_id = torch.multinomial(probs, 1)\n"
"        ids = torch.cat([ids, next_id], dim=1)\n"
"    return \"\".join(itos[i.item()] for i in ids[0])\n"
"\n"
"prompts = [\"ROMEO:\\n\", \"To be or not to \", \"The king \", \"O, \"]\n"
"for prompt in prompts:\n"
"    print(f\"\\nPrompt: {repr(prompt)}\")\n"
"    print(f\"  V12.2:   {generate_text(model, prompt, config)[len(prompt):len(prompt)+100]}\")\n"
"    print(f\"  GPT:     {generate_text(gpt_model, prompt, config, is_gpt=True)[len(prompt):len(prompt)+100]}\")\n"
"    print(f\"  SSM+MLP: {generate_text(ssm_model, prompt, config)[len(prompt):len(prompt)+100]}\")"
)

# Cell 25: Summary
md(
"## Summary\n"
"\n"
"### V12.2: Fixed Spectral Machinery\n"
"\n"
"**Three fixes from V12.1 ablation diagnosis:**\n"
"\n"
"1. **rfft/irfft (conjugate redundancy fix):** V12.1 used full fft/ifft. After block 1,\n"
"   FFT of real signal produces conjugate-symmetric spectrum where modes k and N-k have\n"
"   identical magnitude. Top-k selected both, wasting half the sparsity budget.\n"
"   10 selected modes = ~5 independent DoF. With rfft, 10/17 unique modes = 10 independent DoF.\n"
"   *Candes 2006: compressed sensing guarantees require independent measurements.*\n"
"\n"
"2. **Signed diffusion (transport amplification fix):** V12.1 used softplus(D) forcing D>=0,\n"
"   so transport kernel |exp(-D*w^2)| <= 1 everywhere. Transport could only dampen, never\n"
"   amplify. Equivalent to a learnable low-pass filter.\n"
"   *Hoang 2020: GNNs suffer the same low-pass pathology.* tanh allows bidirectional energy flow.\n"
"\n"
"3. **Proximal at end (settler freedom fix):** V12.1 applied spectral proximal at every\n"
"   Langevin step, immediately projecting the settler state back to the sparse spectral\n"
"   manifold and destroying Hopfield gradient progress. Now settler explores freely\n"
"   during settling, projects once at the end.\n"
"   *Ramsauer 2021: Hopfield retrieval needs to reach the attractor, not be yanked away.*\n"
"\n"
"**Non-negotiables (all preserved):**\n"
"1. Sparse in spectral, dense only transiently in spatial\n"
"2. Field reconstruction IS the inverse Fourier transform (irfft)\n"
"3. Langevin starts from the reconstructed (irfft) field\n"
"4. Context warps the spectral metric (D and A are context-dependent)\n"
"5. Spectral proximal enforced (after settling completes)\n"
"6. Subbundles are independent spectral channels\n"
"7. No pairwise token attention\n"
"\n"
"**Block flow:**\n"
"```\n"
"sparse spectral (136) -> irfft -> SSM context -> spectral transport (signed) ->\n"
"irfft (field reconstruction) -> 2-step Hopfield settling (free exploration) ->\n"
"spectral proximal (once) -> SpatialMLP -> gated residual ->\n"
"rfft + re-sparsify -> sparse spectral (136)\n"
"```"
)

# ═══════════════════════════════════════════════════════════════
# Write notebook
# ═══════════════════════════════════════════════════════════════
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "base",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "cells": cells,
}

outpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "architecture_v12_2.ipynb")
with open(outpath, "w") as f:
    json.dump(nb, f, indent=1)

print(f"Created {outpath} with {len(cells)} cells")

# Verify
import ast
errors = 0
for i, cell in enumerate(cells):
    if cell['cell_type'] == 'code':
        src = ''.join(cell['source'])
        try:
            ast.parse(src)
        except SyntaxError as e:
            print(f"SYNTAX ERROR in cell {i}, line {e.lineno}: {e.msg}")
            errors += 1
if errors == 0:
    print(f"All {sum(1 for c in cells if c['cell_type']=='code')} code cells parse OK")
